//! The lists as the standards give them, and the names and literals made from them.

use ritsu_emit::words::{Words, go, postgresql, python, rust, typescript};
use ritsu_emit::{header, ident, lit};

/// No word twice in what a target is held to, and as many as the standards list.
#[test]
fn the_lists_are_the_standards() {
    for (name, w, n) in [("TypeScript", typescript::NAMES, 51), ("Python", python::NAMES, 39), ("Go", go::NAMES, 69), ("Rust", rust::NAMES, 52), ("PostgreSQL", postgresql::NAMES, 173)] {
        let all: Vec<&str> = w.iter().collect();
        let mut seen = std::collections::BTreeSet::new();
        assert!(all.iter().all(|x| seen.insert(*x)), "{name} has a word twice");
        assert_eq!(all.len(), n, "{name}");
    }
    assert_eq!(python::KEYWORDS.len(), 35);
    assert_eq!(go::KEYWORDS.len(), 25);
    assert!(typescript::NAMES.contains("implements") && !typescript::NAMES.contains("of"));
    assert!(go::NAMES.contains("complex128") && rust::NAMES.contains("Self") && postgresql::NAMES.contains("strict"));
    assert!(Words(&[&["a"], &["b"]]).contains("b"));
}

#[test]
fn names() {
    assert_eq!(ident::pascal("payment_at"), "PaymentAt");
    assert_eq!(ident::pascal("_a__b_"), "AB");
    assert_eq!(ident::go_package("payment_terms"), "paymentterms");
    assert_eq!((ident::go_exported("sku"), ident::go_exported("SKU"), ident::go_exported("引当"), ident::go_exported("ä")), ("Sku".into(), "SKU".into(), "X引当".into(), "Ä".into()));
    assert!(ident::is_ascii_ident("_a1") && !ident::is_ascii_ident("1a") && !ident::is_ascii_ident("在庫"));
    assert_eq!(ident::aside("class", |w| python::KEYWORDS.contains(&w)), "class_");
    assert_eq!(ident::aside("klass", |w| python::KEYWORDS.contains(&w)), "klass");
    assert_eq!(ident::unique(vec!["a".into(), "a".into(), "b".into(), "a".into()], &["b"]), ["a", "a_2", "b_2", "a_3"]);
}

#[test]
fn literals() {
    let s = "a\"b'c\\d\ne\r\tf\u{1}g\u{7f}h本";
    assert_eq!(lit::json(s), "\"a\\\"b'c\\\\d\\ne\\r\\tf\\u0001g\u{7f}h本\"");
    assert_eq!(lit::python(s), "'a\"b\\'c\\\\d\\ne\\r\\tf\\x01g\u{7f}h本'");
    assert_eq!(lit::go(s), "\"a\\\"b'c\\\\d\\ne\\r\\tf\\x01g\\x7fh本\"");
    assert_eq!(lit::sql("本店's"), "'本店''s'");
    assert_eq!(lit::sql_ident("在\"庫"), "\"在\"\"庫\"");
}

#[test]
fn the_generated_line() {
    assert_eq!(header::generated("koyomi"), format!("Code generated by koyomi {}. DO NOT EDIT.", env!("CARGO_PKG_VERSION")));
    let s = header::Source { path: "dates/payment_terms.cal", kind: "dates", name: "payment_terms", version: "1", sha256: &ritsu_base::sha256::hex(b"x") };
    assert_eq!(s.line().get(ritsu_base::text::Lang::En), "Source: dates/payment_terms.cal (dates payment_terms v1, sha256:2d711642b726b044)");
    assert_eq!(s.line().get(ritsu_base::text::Lang::Ja), "もと: dates/payment_terms.cal（dates payment_terms v1、sha256:2d711642b726b044）");
    assert_eq!(header::file_name("rules/送料.rule"), "送料.rule");
    assert_eq!(header::Comment::Slashes.line("x"), "// x\n");
    assert_eq!(header::Comment::Hash.line("x"), "# x\n");
    assert_eq!(header::Comment::Dashes.line("x"), "-- x\n");
}
