//! The line that says a file is generated, which Go's tools look for (`^// Code generated .*
//! DO NOT EDIT\.$`) and the other targets' readers know, and the comments it is written in.

/// `Code generated by koyomi 0.1.0. DO NOT EDIT.`: `by` says what wrote the file.
pub fn generated(by: &str) -> String {
    format!("Code generated {by}. DO NOT EDIT.")
}

/// How a target writes a comment of one line.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Comment {
    /// `// …`: TypeScript, JavaScript, Go, Rust.
    Slashes,
    /// `# …`: Python, YAML.
    Hash,
    /// `-- …`: SQL.
    Dashes,
}

impl Comment {
    /// The line as a comment, with its newline.
    pub fn line(self, text: &str) -> String {
        let mark = match self {
            Comment::Slashes => "//",
            Comment::Hash => "#",
            Comment::Dashes => "--",
        };
        format!("{mark} {text}\n")
    }
}
