//! The head of a generated file (DESIGN 9.2): the line that says the file is generated, which Go's
//! tools look for (`^// Code generated .* DO NOT EDIT\.$`) and the other targets' readers know,
//! and the line that says what the file is made from; and the comments they are written in.
//!
//! Every generator of ritsu begins its files with the same two lines:
//!
//! ```text
//! // Code generated by koyomi 0.1.0. DO NOT EDIT.
//! // Source: dates/payment_terms.cal (dates payment_terms v1, sha256:20eacc1719046107)
//! ```
//!
//! (`ritsu gen` of `crates/ritsu/tests/projects/stockroom`; a language's own command writes the
//! file's name, `payment_terms.cal`.)
//!
//! The version is ritsu's, which every language of the workspace carries (DESIGN 9.4, 13.1): a
//! file generated by one ritsu and a file generated by another differ in their first line, and a
//! package (`ritsu gen`, DESIGN 9.3) whose files say one version was generated in one go. The
//! path is what the generator is told to write: a language's own command writes the file's name
//! (no path of the machine that ran it), `ritsu gen` the path from the project's root, which names
//! the file the way every naming of ritsu does (DESIGN 6.2). The digest is the first sixteen hex
//! digits of the SHA-256 of the file's bytes, the length of every pin of ritsu's
//! (`ritsu_base::sha256::short`). A file that is not made from a source (a runtime every client
//! carries, a test of the helpers) has the first line only.

use ritsu_base::text::Text;
use ritsu_base::tr;

/// ritsu's version: the one version of the workspace (DESIGN 13.1), which the head of every
/// generated file carries.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// `Code generated by koyomi 0.1.0. DO NOT EDIT.`: `tool` is what wrote the file (`rulec`, `koyomi`,
/// `chobo`, `dandori`, or `ritsu` for what a package itself is made of), the version ritsu's.
pub fn generated(tool: &str) -> String {
    format!("Code generated by {tool} {VERSION}. DO NOT EDIT.")
}

/// What a generated file is made from.
#[derive(Clone, Copy, Debug)]
pub struct Source<'a> {
    /// The path the head names: the file's name in a language's own command, the path from the
    /// project's root in `ritsu gen`.
    pub path: &'a str,
    /// The language's word for what the file declares: `rule`, `dates`, `calendar`, `book`,
    /// `workflow`.
    pub kind: &'a str,
    pub name: &'a str,
    pub version: &'a str,
    /// The SHA-256 of the file's bytes, as 64 hex digits or already cut to sixteen.
    pub sha256: &'a str,
}

impl Source<'_> {
    /// `Source: dates/payment_terms.cal (dates payment_terms v1, sha256:20eacc1719046107)`, in the
    /// language the generated code is written in.
    pub fn line(&self) -> Text {
        let Source { path, kind, name, version, sha256 } = *self;
        let sha = &sha256[..16.min(sha256.len())];
        tr!("もと: {path}（{kind} {name} v{version}、sha256:{sha}）", "Source: {path} ({kind} {name} v{version}, sha256:{sha})")
    }
}

/// The name of a file at `path` (a path as the person gave it), which a language's own command
/// writes in the head: no directory, so that no path of the machine that ran it is written.
pub fn file_name(path: &str) -> String {
    std::path::Path::new(path).file_name().map(|f| f.to_string_lossy().to_string()).unwrap_or_else(|| path.to_string())
}

/// What the caller of a generator knows of the file it hands over: the path the head names, and
/// the SHA-256 of the file's bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Origin {
    pub path: String,
    pub sha256: String,
}

impl Origin {
    /// The file at `path` as a language's own command names it, by its name.
    pub fn named(path: &str, bytes: &[u8]) -> Origin {
        Origin { path: file_name(path), sha256: ritsu_base::sha256::hex(bytes) }
    }

    /// The file at `rel` from a project's root, as `ritsu gen` names it.
    pub fn at(rel: &str, bytes: &[u8]) -> Origin {
        Origin { path: rel.to_string(), sha256: ritsu_base::sha256::hex(bytes) }
    }

    /// What the file declares, in the head's words.
    pub fn source<'a>(&'a self, kind: &'a str, name: &'a str, version: &'a str) -> Source<'a> {
        Source { path: &self.path, kind, name, version, sha256: &self.sha256 }
    }
}

/// How a target writes a comment of one line.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Comment {
    /// `// …`: TypeScript, JavaScript, Go, Rust.
    Slashes,
    /// `# …`: Python, YAML.
    Hash,
    /// `-- …`: SQL.
    Dashes,
}

impl Comment {
    /// The line as a comment, with its newline.
    pub fn line(self, text: &str) -> String {
        let mark = match self {
            Comment::Slashes => "//",
            Comment::Hash => "#",
            Comment::Dashes => "--",
        };
        format!("{mark} {text}\n")
    }
}
