//! The head of a generated file (DESIGN 9.2): the line that says the file is generated, which Go's
//! tools look for (`^// Code generated .* DO NOT EDIT\.$`) and the other targets' readers know,
//! and the line that says what the file is made from; and the comments they are written in.
//!
//! Every generator of ritsu begins its files with the same two lines:
//!
//! ```text
//! // Code generated by koyomi 0.1.0. DO NOT EDIT.
//! // Source: dates/payment_terms.cal (dates payment_terms v1, sha256:20eacc1719046107)
//! ```
//!
//! (`ritsu gen` of `crates/ritsu/tests/projects/stockroom`; a language's own command writes the
//! file's name, `payment_terms.cal`.)
//!
//! The version is ritsu's, which every language of the workspace carries (DESIGN 9.4, 13.1): a
//! file generated by one ritsu and a file generated by another differ in their first line, and a
//! package (`ritsu gen`, DESIGN 9.3) whose files say one version was generated in one go. The
//! path is what the generator is told to write: a language's own command writes the file's name
//! (no path of the machine that ran it), `ritsu gen` the path from the project's root, which names
//! the file the way every naming of ritsu does (DESIGN 6.2). The digest is the first sixteen hex
//! digits of the SHA-256 of the file's bytes, the length of every pin of ritsu's
//! (`ritsu_base::sha256::short`). A file that is not made from a source (a runtime every client
//! carries, a test of the helpers) has the first line only.

use ritsu_base::text::Text;
use ritsu_base::tr;

/// ritsu's version: the one version of the workspace (DESIGN 13.1), which the head of every
/// generated file carries.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// `Code generated by koyomi 0.1.0. DO NOT EDIT.`: `tool` is what wrote the file (`rulec`, `koyomi`,
/// `chobo`, `dandori`, or `ritsu` for what a package itself is made of), the version ritsu's.
pub fn generated(tool: &str) -> String {
    format!("Code generated by {tool} {VERSION}. DO NOT EDIT.")
}

/// What a generated file is made from.
#[derive(Clone, Copy, Debug)]
pub struct Source<'a> {
    /// The path the head names: the file's name in a language's own command, the path from the
    /// project's root in `ritsu gen`.
    pub path: &'a str,
    /// The language's word for what the file declares: `rule`, `dates`, `calendar`, `book`,
    /// `workflow`.
    pub kind: &'a str,
    pub name: &'a str,
    pub version: &'a str,
    /// The SHA-256 of the file's bytes, as 64 hex digits or already cut to sixteen.
    pub sha256: &'a str,
}

impl Source<'_> {
    /// `Source: dates/payment_terms.cal (dates payment_terms v1, sha256:20eacc1719046107)`, in the
    /// language the generated code is written in. The path is put on one line ([`one_line`]): a
    /// file's name may hold a line break, and the line is a comment.
    pub fn line(&self) -> Text {
        let Source { path, kind, name, version, sha256 } = *self;
        let path = one_line(path);
        let sha = &sha256[..16.min(sha256.len())];
        tr!("もと: {path}（{kind} {name} v{version}、sha256:{sha}）", "Source: {path} ({kind} {name} v{version}, sha256:{sha})")
    }
}

/// The characters some target ends a line at: `\n` and `\r` (Python ends one at a `\r` alone), and
/// NEL, LINE SEPARATOR and PARAGRAPH SEPARATOR (U+0085, U+2028, U+2029), the last two of which end
/// a line of JavaScript and TypeScript, and all three one of YAML 1.1.
pub const LINE_BREAKS: [char; 5] = ['\n', '\r', '\u{85}', '\u{2028}', '\u{2029}'];

/// `text` on one line, each of [`LINE_BREAKS`] written `U+XXXX` (`U+000A`, `U+2028`, …). Text a
/// source file holds (a file's name, a path or a URL it cites) goes into a comment of one line; a
/// break in it would end the comment, and what follows would be a line of the generated code that
/// no check of the source has seen (DESIGN 9.2).
///
/// The form holds no `\` and no `\u`, so it is the same in every target and safe where a `\uXXXX`
/// in a comment is read before the comment is (Java, Scala 2): the earlier `\u{XXXX}` was a
/// malformed escape there and stopped the compiler. A literal `\uXXXX` already in `text` is left
/// as it is here; a target that reads it in a comment takes the line through [`for_unicode_comment`].
pub fn one_line(text: &str) -> std::borrow::Cow<'_, str> {
    if !text.contains(LINE_BREAKS) {
        return std::borrow::Cow::Borrowed(text);
    }
    let mut s = String::with_capacity(text.len() + 8);
    for c in text.chars() {
        if LINE_BREAKS.contains(&c) {
            s.push_str(&format!("U+{:04X}", c as u32));
        } else {
            s.push(c);
        }
    }
    std::borrow::Cow::Owned(s)
}

/// `text` made safe in a comment of a target that reads a Unicode escape (`\uXXXX`) before it
/// recognises the comment — Java (JLS 3.3) and Scala 2 — by doubling every `\`. Such a target
/// translates `\uXXXX` anywhere in the source, a comment included, so a `\u000a` in a cited path
/// or URL would become a line break that ends the comment, and the code after it would be text no
/// check has seen. A `\` begins an escape only when an even number of `\` stands before it, so
/// doubling leaves the `u` after every run of `\` preceded by an odd count, and no escape begins.
/// [`one_line`] has already put the line breaks as `U+XXXX`, which holds no `\`, so this touches
/// only the backslashes the source text itself holds. Every other target the generators of ritsu
/// write leaves a comment's bytes alone and needs none of this.
pub fn for_unicode_comment(text: &str) -> String {
    text.replace('\\', "\\\\")
}

/// The name of a file at `path` (a path as the person gave it), which a language's own command
/// writes in the head: no directory, so that no path of the machine that ran it is written.
pub fn file_name(path: &str) -> String {
    std::path::Path::new(path).file_name().map(|f| f.to_string_lossy().to_string()).unwrap_or_else(|| path.to_string())
}

/// What the caller of a generator knows of the file it hands over: the path the head names, and
/// the SHA-256 of the file's bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Origin {
    pub path: String,
    pub sha256: String,
}

impl Origin {
    /// The file at `path` as a language's own command names it, by its name.
    pub fn named(path: &str, bytes: &[u8]) -> Origin {
        Origin { path: file_name(path), sha256: ritsu_base::sha256::hex(bytes) }
    }

    /// The file at `rel` from a project's root, as `ritsu gen` names it.
    pub fn at(rel: &str, bytes: &[u8]) -> Origin {
        Origin { path: rel.to_string(), sha256: ritsu_base::sha256::hex(bytes) }
    }

    /// What the file declares, in the head's words.
    pub fn source<'a>(&'a self, kind: &'a str, name: &'a str, version: &'a str) -> Source<'a> {
        Source { path: &self.path, kind, name, version, sha256: &self.sha256 }
    }
}

/// How a target writes a comment of one line.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Comment {
    /// `// …`: TypeScript, JavaScript, Go, Rust.
    Slashes,
    /// `# …`: Python, YAML.
    Hash,
    /// `-- …`: SQL.
    Dashes,
}

impl Comment {
    /// What begins each line of the comment.
    pub fn mark(self) -> &'static str {
        match self {
            Comment::Slashes => "//",
            Comment::Hash => "#",
            Comment::Dashes => "--",
        }
    }

    /// The line as a comment, with its newline; a break in it is written as its escape
    /// ([`one_line`]), so the comment stays one line.
    pub fn line(self, text: &str) -> String {
        format!("{} {}\n", self.mark(), one_line(text))
    }

    /// The text as a comment of as many lines as it has, each with its newline: a description a
    /// source file gives in several lines (`\n` in a string of dandori's) stays a comment on each
    /// of them. A line ends at each of [`LINE_BREAKS`], and at `\r\n` once.
    pub fn lines(self, text: &str) -> String {
        let mut out = String::new();
        let mut rest = text;
        loop {
            let (line, next) = match rest.find(LINE_BREAKS) {
                Some(at) => {
                    let c = rest[at..].chars().next().unwrap_or('\n');
                    let skip = if rest[at..].starts_with("\r\n") { 2 } else { c.len_utf8() };
                    (&rest[..at], Some(&rest[at + skip..]))
                }
                None => (rest, None),
            };
            out.push_str(self.mark());
            if !line.is_empty() {
                out.push(' ');
                out.push_str(line);
            }
            out.push('\n');
            match next {
                Some(n) => rest = n,
                None => break,
            }
        }
        out
    }
}
