//! The page as Markdown that GitHub shows as it is (ritsu's DESIGN 4.8): a comment that names the
//! `.gate` it was drawn from, then the blocks. A fold is a `<details>` section, and so is the page
//! of a rule, a dates file or a calendar, as `dandori doc` holds the pages of its rules.

use super::{Block, Page};
use ritsu_base::text::Lang;

/// Text written as Markdown prose (ritsu's DESIGN 9.2): a `<` that could begin HTML (followed by a
/// letter, `/`, `!` or `?`) is written `&lt;` outside the code spans, so a description that holds
/// `</script>` or a tag stays text where HTML is passed through; the code spans, and a `<` before
/// anything else (`<= 3`, `a < b`), are left as they are. A carriage return, which Markdown takes
/// for the end of a line, is a space: what a `.gate` writes does not start a line of the page. The
/// same rule as the Markdown of `sakai doc`, `dandori doc` and `rulec doc`.
pub fn prose(s: &str) -> String {
    let cs: Vec<char> = s.replace(['\r', '\n'], " ").chars().collect();
    let mut o = String::with_capacity(s.len());
    let mut i = 0;
    while i < cs.len() {
        if cs[i] == '`' {
            // a code span runs to the next run of as many backquotes; without one, the backquotes
            // are text
            let n = cs[i..].iter().take_while(|c| **c == '`').count();
            let mut j = i + n;
            let mut end = None;
            while j < cs.len() {
                let m = cs[j..].iter().take_while(|c| **c == '`').count();
                if m == n {
                    end = Some(j + m);
                    break;
                }
                j += m.max(1);
            }
            let stop = end.unwrap_or(i + n);
            o.extend(&cs[i..stop]);
            i = stop;
            continue;
        }
        if cs[i] == '<' && cs.get(i + 1).is_some_and(|c| c.is_ascii_alphabetic() || matches!(c, '/' | '!' | '?')) {
            o.push_str("&lt;");
        } else {
            o.push(cs[i]);
        }
        i += 1;
    }
    o
}

/// A cell of a table: prose, with its `|` kept from ending the cell.
fn cell(s: &str) -> String {
    prose(s).replace('|', "\\|")
}

/// Text in HTML, as a summary of a `<details>` holds it (GitHub does not read Markdown there): its
/// code spans as `<code>`.
fn html_inline(s: &str) -> String {
    super::html::inline(s)
}

/// A fence longer than any run of backquotes in the text.
fn fence(text: &str) -> String {
    let mut longest = 0;
    let mut run = 0;
    for c in text.chars() {
        if c == '`' {
            run += 1;
            longest = longest.max(run);
        } else {
            run = 0;
        }
    }
    "`".repeat((longest + 1).max(3))
}

pub fn write(p: &Page) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let file = p.file.replace("--", "- -");
    let mut out = match p.lang {
        Lang::En => format!(
            "<!-- Generated by sekisho {version} from {file} (sha256:{}). This is a read-only rendering; the source of truth is the .gate file. Edits cannot be carried back. -->\n",
            p.sha
        ),
        Lang::Ja => format!(
            "<!-- sekisho {version} が {file}（sha256:{}）から生成したページです。読むためのもので、もとになるのは .gate のほうです。ここを編集しても .gate には戻せません。 -->\n",
            p.sha
        ),
    };
    out.push_str(&format!("# {}\n", prose(&p.title)));
    if let Some(d) = &p.description {
        out.push_str(&format!("\n{}\n", prose(d)));
    }
    for b in &p.blocks {
        out.push('\n');
        block(&mut out, p, b);
    }
    out
}

fn block(out: &mut String, p: &Page, b: &Block) {
    match b {
        Block::Heading { level, text, .. } => out.push_str(&format!("{} {}\n", "#".repeat(*level as usize), prose(text))),
        Block::Para(text) => out.push_str(&format!("{}\n", prose(text))),
        Block::Note(text) => out.push_str(&format!("> [!NOTE]\n> {}\n", prose(text))),
        Block::List(items) => {
            for i in items {
                out.push_str(&format!("- {}\n", prose(i)));
            }
        }
        Block::Table { head, rows, .. } => {
            out.push_str(&format!("| {} |\n", head.iter().map(|h| cell(h)).collect::<Vec<_>>().join(" | ")));
            out.push_str(&format!("|{}\n", "---|".repeat(head.len())));
            for r in rows {
                out.push_str(&format!("| {} |\n", r.iter().map(|c| cell(c)).collect::<Vec<_>>().join(" | ")));
            }
        }
        Block::Fold { summary, body } => {
            out.push_str(&format!("<details>\n<summary>{}</summary>\n", html_inline(summary)));
            for x in body {
                out.push('\n');
                block(out, p, x);
            }
            out.push_str("\n</details>\n");
        }
        Block::Code { lang, caption, text } => {
            if !caption.is_empty() {
                out.push_str(&format!("`{caption}`\n\n"));
            }
            let f = fence(text);
            let tag = if *lang == "text" { "text" } else { lang };
            out.push_str(&format!("{f}{tag}\n{text}\n{f}\n"));
        }
        Block::Side(xs) => {
            for (i, x) in xs.iter().enumerate() {
                if i > 0 {
                    out.push('\n');
                }
                block(out, p, x);
            }
        }
        Block::Embed(k) => {
            let e = &p.embedded[*k];
            let summary = super::html::embedded_label(p.lang, e);
            out.push_str(&format!("<details>\n<summary>{summary}</summary>\n\n"));
            match &e.page {
                Ok(page) => out.push_str(&format!("{}\n", page.trim_end())),
                Err(why) => {
                    let said = match p.lang {
                        Lang::En => format!("{} could not draw the page of this file.", e.tool),
                        Lang::Ja => format!("{} は、このファイルのページを描けませんでした。", e.tool),
                    };
                    let f = fence(why);
                    out.push_str(&format!("{said}\n\n{f}text\n{why}\n{f}\n"));
                }
            }
            out.push_str("\n</details>\n");
        }
    }
}
