//! Argo Workflows: a WorkflowTemplate, and `caller/`, the program that runs the tasks dandori
//! writes (`lambda`, `http`, `aws`, `agent`) and the rules, in containers of the workflow.
//!
//! Argo has no variables, no step that ends the workflow early, and no names for errors, so
//! the workflow keeps its own state in its global output parameters:
//!
//! - every variable is a global parameter, `v<n>`, holding its value as JSON; the variables a
//!   parallel round keeps for itself get the round's suffix (`v<n>_p<site>i<index>`);
//! - `dd_ctl` says how the flow goes on: `next`, or `break`, `succeed`, `fail`, `task` (a task's
//!   error nothing handled); `dd_error` holds the error of `fail` and `task`, `dd_output` the
//!   outputs of `succeed`.
//!
//! Argo evaluates a step's `when` and arguments again each time it looks at the workflow while
//! the step runs, and a template of steps reads the global parameters as they were when Argo
//! came to it, not as its own steps have set them since. So the global parameters are read in
//! one place only: the output expressions of a template whose one step never runs, which
//! computes values without a pod. Argo evaluates those once, as it comes to the template,
//! with everything set before. Every other step takes what it needs from such outputs, which
//! stay as they are:
//!
//! - a call's arguments, the arm of a match and the number of a loop's rounds are computed
//!   just before them;
//! - every statement that can stop the flow has an output `go`, and the statements after it
//!   in its block run when it is `true`;
//! - loops run their rounds one at a time with `withSequence` and `parallelism`, not by
//!   recursion, whose depth Argo limits to 100;
//! - a task is a container: the user's image (`image`), or the caller image for the tasks
//!   dandori writes and the rules. The call comes in the environment variable DANDORI_CALL;
//!   the answer goes to /tmp/dandori/answer.json; a declared error goes to
//!   /tmp/dandori/error.json as { "error", "message" }, with exit code 3; a pod stopped at its
//!   deadline (exit code 143 or 137) is a timeout; anything else is a failure. The deadline is
//!   the pod's `activeDeadlineSeconds`, which also stops a pod that never started; a
//!   template's `timeout` that runs out before the pod starts would fail the steps around it,
//!   past `continueOn`.
//!
//! When the flow ends as failed, a last container fails the workflow with the error, which
//! also stays in `dd_error`.

use crate::diag::Diag;
use crate::model::*;
use crate::render::{self, ident};
use serde_json::{json, Map, Value};
use std::collections::{BTreeMap, BTreeSet};

/// What a callback's wait answers when its time runs out.
pub const TIMEOUT: &str = "dandori:timeout";

pub fn build(m: &Model) -> Result<Vec<(String, String)>, Vec<Diag>> {
    fit(m)?;
    let (doc, comment) = Gen::new(m).workflow();
    let yaml = format!("{comment}{}", yaml(&doc, 0));
    let header = format!("// Code generated by dandori from {}. DO NOT EDIT.\n", m.source_file);
    let mut files = vec![(format!("{}.argo.yaml", ident(&m.name)), yaml)];
    for (name, text) in crate::temporal::argo_caller(m, &header) {
        files.push((name, text));
    }
    Ok(files)
}

/// The WorkflowTemplate as JSON, for a runner that changes it before it applies it.
pub fn document(m: &Model) -> Result<Value, Vec<Diag>> {
    fit(m)?;
    Ok(Gen::new(m).workflow().0)
}

/// What Argo cannot run: a task with no way to run there, the errors of a workflow a task
/// starts, and a retried callback.
fn fit(m: &Model) -> Result<(), Vec<Diag>> {
    let mut errs = Vec::new();
    for t in &m.tasks {
        match t.via(Platform::Argo) {
            None => errs.push(Diag::error(
                "E050",
                t.line,
                1,
                format!("`{}` needs `image`, `lambda`, `http`, `aws`, `agent` or `workflow template` to run on Argo Workflows", t.name),
                format!("`{}` を Argo Workflows で動かすには `image`・`lambda`・`http`・`aws`・`agent`・`workflow template` のどれかが要ります", t.name),
            )),
            Some(Via::ArgoTemplate(_)) if !t.errors.is_empty() => errs.push(Diag::error(
                "E050",
                t.line,
                1,
                format!("Argo reports a workflow's failure without its error, so the errors of `{}` cannot be told apart there; leave out `errors` and handle `failure`", t.name),
                format!("Argo はワークフローの失敗をそのエラーなしで伝えるので、`{}` のエラーを見分けられません。`errors` を外し、`failure` で受けてください", t.name),
            )),
            _ => {}
        }
        if t.callback && t.retry.is_some() {
            errs.push(Diag::error(
                "E050",
                t.line,
                1,
                format!("Argo would retry only the step that hands the id of `{}` on, not the wait for its answer; leave out `retry`", t.name),
                format!("Argo でやり直せるのは `{}` の ID を渡すステップだけで、答えを待つところはやり直せません。`retry` を外してください", t.name),
            ));
        }
    }
    if errs.is_empty() {
        Ok(())
    } else {
        Err(errs)
    }
}

/// For every variable, how deep in `for … in parallel` the rounds that own it are (0: the workflow's).
fn owners(m: &Model) -> BTreeMap<String, usize> {
    let mut out = BTreeMap::new();
    fn go(ss: &[TStmt], depth: usize, out: &mut BTreeMap<String, usize>) {
        for s in ss {
            match &s.kind {
                TK::For { body, locals, parallel: Some(_), .. } => {
                    for l in locals {
                        out.insert(l.clone(), depth + 1);
                    }
                    go(body, depth + 1, out);
                }
                TK::For { body, .. } | TK::Repeat { body, .. } => go(body, depth, out),
                TK::Match { arms, .. } => arms.iter().for_each(|a| go(&a.body, depth, out)),
                TK::Call { handlers, .. } => handlers.iter().for_each(|h| go(&h.body, depth, out)),
                _ => {}
            }
        }
    }
    go(&m.flow, 0, &mut out);
    if let Some(f) = &m.on_failure {
        go(f, 0, &mut out);
    }
    out
}

fn q(s: &str) -> String {
    serde_json::to_string(s).unwrap()
}

/// An expression with each JSON value it reads more than once read once, at its head:
/// `let g0 = sprig.fromJson(…); …`. The values are the global parameters and the template's
/// inputs, which are all there by the time a template reads them. Quoted strings are left alone.
fn hoist(expr: &str) -> String {
    const HEADS: [&str; 2] = ["sprig.fromJson(workflow.outputs.parameters[", "sprig.fromJson(inputs.parameters."];
    let mut reads: Vec<(usize, usize)> = Vec::new();
    let mut in_str = false;
    let mut escaped = false;
    let mut i = 0;
    while i < expr.len() {
        let c = expr[i..].chars().next().unwrap();
        if in_str {
            match c {
                _ if escaped => escaped = false,
                '\\' => escaped = true,
                '"' => in_str = false,
                _ => {}
            }
            i += c.len_utf8();
            continue;
        }
        if c == '"' {
            in_str = true;
            i += 1;
            continue;
        }
        let rest = &expr[i..];
        let end = if rest.starts_with(HEADS[0]) {
            rest.find("])").map(|e| i + e + 2)
        } else if let Some(name) = rest.strip_prefix(HEADS[1]) {
            let n = name.find(|c: char| !(c.is_ascii_alphanumeric() || c == '_')).unwrap_or(name.len());
            name[n..].starts_with(')').then(|| i + HEADS[1].len() + n + 1)
        } else {
            None
        };
        match end {
            Some(e) => {
                reads.push((i, e));
                i = e;
            }
            None => i += c.len_utf8(),
        }
    }
    let mut names: Vec<(&str, usize)> = Vec::new();
    for (a, b) in &reads {
        let text = &expr[*a..*b];
        match names.iter_mut().find(|(t, _)| *t == text) {
            Some((_, n)) => *n += 1,
            None => names.push((text, 1)),
        }
    }
    let twice: Vec<&str> = names.iter().filter(|(_, n)| *n > 1).map(|(t, _)| *t).collect();
    if twice.is_empty() {
        return expr.to_string();
    }
    let mut out = String::new();
    for (k, t) in twice.iter().enumerate() {
        out.push_str(&format!("let g{k} = {t}; "));
    }
    let mut last = 0;
    for (a, b) in &reads {
        if let Some(k) = twice.iter().position(|t| *t == &expr[*a..*b]) {
            out.push_str(&expr[last..*a]);
            out.push_str(&format!("g{k}"));
            last = *b;
        }
    }
    out.push_str(&expr[last..]);
    out
}

/// A name Argo takes for a template, a step or a parameter: ASCII letters, digits and `-`.
fn slug(s: &str) -> String {
    let t: String = s.chars().map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '-' }).collect();
    t.split('-').filter(|x| !x.is_empty()).collect::<Vec<_>>().join("-")
}

/// An output of a template that computes: its name, the global parameter it sets, and its expression.
type Out = (String, Option<String>, String);

struct Gen<'a> {
    m: &'a Model,
    templates: Vec<Value>,
    used: BTreeSet<String>,
    owner: BTreeMap<String, usize>,
    var_ix: BTreeMap<String, usize>,
    /// the templates of the tasks and rules made so far
    made: BTreeSet<String>,
}

impl<'a> Gen<'a> {
    fn new(m: &'a Model) -> Gen<'a> {
        let mut g = Gen { m, templates: Vec::new(), used: BTreeSet::new(), owner: owners(m), var_ix: BTreeMap::new(), made: BTreeSet::new() };
        for (i, (v, _)) in m.vars.iter().enumerate() {
            g.var_ix.insert(v.clone(), i);
        }
        for n in ["main", "dd-end", "dd-nothing", "dd-recover"] {
            g.used.insert(n.to_string());
        }
        g
    }

    fn name(&mut self, base: &str) -> String {
        let stem = slug(base);
        let stem = if stem.is_empty() { "t".to_string() } else { stem };
        let mut n = stem.clone();
        let mut k = 2;
        while self.used.contains(&n) {
            n = format!("{stem}-{k}");
            k += 1;
        }
        self.used.insert(n.clone());
        n
    }

    // -------------------------------------------------------------------------------------
    // What a template reads and sets

    /// The parameters every template of the flow takes: the rounds of the loops around it,
    /// for keys, and the suffix of each parallel round around it.
    fn inputs(depth: usize, extra: &[&str]) -> Value {
        let mut ps = vec![json!({ "name": "rounds" })];
        for k in 1..=depth {
            ps.push(json!({ "name": format!("s{k}") }));
        }
        for e in extra {
            ps.push(json!({ "name": e }));
        }
        json!({ "parameters": ps })
    }

    fn pass(depth: usize) -> Vec<Value> {
        let mut ps = vec![json!({ "name": "rounds", "value": "{{inputs.parameters.rounds}}" })];
        for k in 1..=depth {
            ps.push(json!({ "name": format!("s{k}"), "value": format!("{{{{inputs.parameters.s{k}}}}}") }));
        }
        ps
    }

    fn pass_with(depth: usize, extra: &[&str]) -> Vec<Value> {
        let mut ps = Gen::pass(depth);
        for e in extra {
            ps.push(json!({ "name": e, "value": format!("{{{{inputs.parameters.{e}}}}}") }));
        }
        ps
    }

    /// The global parameter `base` of the scope `depth`, as an expression that reads it.
    fn global_ref(base: &str, depth: usize) -> String {
        if depth == 0 {
            format!("workflow.outputs.parameters[{}]", q(base))
        } else {
            format!("workflow.outputs.parameters[{} + inputs.parameters.s{depth}]", q(base))
        }
    }

    /// The global parameter `base` of the scope `depth`, as a `globalName`.
    fn global_name(base: &str, depth: usize) -> String {
        if depth == 0 {
            base.to_string()
        } else {
            format!("{base}{{{{inputs.parameters.s{depth}}}}}")
        }
    }

    fn var_base(&self, name: &str) -> String {
        let i = self.var_ix[name];
        let ascii: String = name.chars().filter(|c| c.is_ascii_alphanumeric()).collect();
        if ascii.is_empty() || ascii.len() != name.len() {
            format!("v{i}")
        } else {
            format!("v{i}-{ascii}")
        }
    }

    fn var_depth(&self, name: &str) -> usize {
        self.owner.get(name).cloned().unwrap_or(0)
    }

    /// A variable's JSON text.
    fn var_raw(&self, name: &str) -> String {
        Gen::global_ref(&self.var_base(name), self.var_depth(name))
    }

    fn var_global(&self, name: &str) -> String {
        Gen::global_name(&self.var_base(name), self.var_depth(name))
    }

    fn ctl(depth: usize) -> String {
        Gen::global_ref("dd_ctl", depth)
    }

    fn set_ctl(depth: usize, expr: String) -> Out {
        ("ctl".into(), Some(Gen::global_name("dd_ctl", depth)), expr)
    }

    fn set_error(depth: usize, expr: String) -> Out {
        ("error".into(), Some(Gen::global_name("dd_error", depth)), expr)
    }

    /// The output `go` of a template that computes: `true` when the flow goes on.
    fn go(cond: &str) -> Out {
        ("go".into(), None, format!("({cond}) ? \"true\" : \"false\""))
    }

    // -------------------------------------------------------------------------------------
    // Values, as expr-lang

    fn ex(&self, e: &TExpr) -> String {
        match e {
            TExpr::Str(s) => q(s),
            TExpr::Int(n) => n.to_string(),
            TExpr::Bool(b) => b.to_string(),
            TExpr::Enum(v, _) => q(v),
            TExpr::None(_) => "nil".into(),
            TExpr::Var { name, fields, .. } => {
                let mut s = format!("sprig.fromJson({})", self.var_raw(name));
                for f in fields {
                    s = format!("{s}[{}]", q(f));
                }
                s
            }
            TExpr::Record { fields, .. } => format!("{{{}}}", fields.iter().map(|(f, x)| format!("{}: {}", q(f), self.ex(x))).collect::<Vec<_>>().join(", ")),
            TExpr::List { items, .. } => format!("[{}]", items.iter().map(|x| self.ex(x)).collect::<Vec<_>>().join(", ")),
            TExpr::Interp(parts) => {
                let mut out: Vec<String> = Vec::new();
                for p in parts {
                    match p {
                        IPart::Lit(s) => out.push(q(s)),
                        IPart::Hole(x) => match x.ty() {
                            Ty::Str | Ty::Timestamp | Ty::Enum(_) => out.push(self.ex(x)),
                            _ => out.push(format!("string({})", self.ex(x))),
                        },
                    }
                }
                if !matches!(parts.first(), Some(IPart::Lit(_))) {
                    out.insert(0, "\"\"".into());
                }
                format!("({})", out.join(" + "))
            }
        }
    }

    /// A test that `x` is a well-formed value of `t`.
    fn check(&self, x: &str, t: &Ty) -> String {
        let m = self.m;
        match t {
            Ty::Str => format!("type({x}) == \"string\""),
            Ty::Timestamp => format!("(type({x}) == \"string\" && {x} matches {})", q(&render::TIMESTAMP_RE.replace("\\\\", "\\"))),
            Ty::Int | Ty::Num(_) => format!("(type({x}) in [\"int\", \"float\"] && {x} == int({x}))"),
            Ty::Bool => format!("type({x}) == \"bool\""),
            Ty::Enum(e) => format!("{x} in [{}]", m.enums[*e].values.iter().map(|v| q(v)).collect::<Vec<_>>().join(", ")),
            Ty::Json => "true".into(),
            Ty::Opt(inner) => format!("({x} == nil || {})", self.check(x, inner)),
            Ty::List(inner) => format!("(type({x}) == \"array\" && all({x}, {{{}}}))", self.check("#", inner)),
            Ty::Record(r) => {
                let mut parts = vec![format!("type({x}) == \"map\"")];
                for (f, ft) in &m.records[*r].fields {
                    let fx = format!("{x}[{}]", q(f));
                    match ft {
                        Ty::Opt(_) => parts.push(self.check(&fx, ft)),
                        Ty::Json => parts.push(format!("{} in {x}", q(f))),
                        _ => parts.push(format!("({} in {x} && {})", q(f), self.check(&fx, ft))),
                    }
                }
                format!("({})", parts.join(" && "))
            }
        }
    }

    // -------------------------------------------------------------------------------------
    // Templates

    /// A template that computes its outputs without a pod: its one step never runs. It is the
    /// only kind of template that reads the global parameters.
    fn compute(&mut self, name: &str, depth: usize, extra: &[&str], outputs: Vec<Out>) -> String {
        let n = self.name(name);
        let ps: Vec<Value> = outputs
            .into_iter()
            .map(|(p, global, expr)| {
                let mut from = Map::new();
                from.insert("expression".into(), json!(hoist(&expr)));
                // a statement that did not run does not let the flow go on
                if p == "go" {
                    from.insert("default".into(), json!("false"));
                }
                let mut o = Map::new();
                o.insert("name".into(), json!(p));
                if let Some(g) = global {
                    o.insert("globalName".into(), json!(g));
                }
                o.insert("valueFrom".into(), Value::Object(from));
                Value::Object(o)
            })
            .collect();
        self.templates.push(json!({
            "name": n,
            "inputs": Gen::inputs(depth, extra),
            "steps": [[Gen::noop()]],
            "outputs": { "parameters": ps },
        }));
        n
    }

    fn noop() -> Value {
        json!({ "name": "noop", "template": "dd-nothing", "when": "false" })
    }

    fn step(name: &str, template: &str, args: Vec<Value>, when: Option<String>) -> Value {
        let mut o = Map::new();
        o.insert("name".into(), json!(name));
        o.insert("template".into(), json!(template));
        if !args.is_empty() {
            o.insert("arguments".into(), json!({ "parameters": args }));
        }
        if let Some(w) = when {
            o.insert("when".into(), json!(w));
        }
        Value::Object(o)
    }

    /// The output `go` of a template of steps, as one of its steps has it.
    fn go_from(step: &str) -> Value {
        json!({ "name": "go", "valueFrom": { "parameter": format!("{{{{steps.{step}.outputs.parameters.go}}}}"), "default": "false" } })
    }

    /// The output `go` of a template of steps, as an expression over its steps' outputs.
    fn go_expr(expr: String) -> Value {
        json!({ "name": "go", "valueFrom": { "expression": expr, "default": "false" } })
    }

    /// A block: its statements in order; after a statement that can stop the flow, the rest
    /// run when it says the flow goes on.
    fn block(&mut self, ss: &[TStmt], depth: usize, base: &str) -> String {
        let mut steps: Vec<Value> = Vec::new();
        let mut last: Option<String> = None;
        for s in ss {
            if let Some((t, stops)) = self.stmt(s, depth) {
                let name = format!("s{}", s.site);
                let when = last.as_ref().map(|l| format!("{{{{steps.{l}.outputs.parameters.go}}}}"));
                steps.push(json!([Gen::step(&name, &t, Gen::pass(depth), when)]));
                if stops {
                    last = Some(name);
                }
            }
            if matches!(s.kind, TK::Succeed { .. } | TK::Fail { .. } | TK::Break) {
                break;
            }
        }
        if steps.is_empty() {
            steps.push(json!([Gen::noop()]));
        }
        let go = match &last {
            Some(l) => Gen::go_from(l),
            None => Gen::go_expr("\"true\"".into()),
        };
        let n = self.name(base);
        self.templates.push(json!({ "name": n, "inputs": Gen::inputs(depth, &[]), "steps": steps, "outputs": { "parameters": [go] } }));
        n
    }

    fn fail_with(&mut self, name: &str, depth: usize, error: &str, cause: String) -> String {
        self.compute(
            name,
            depth,
            &[],
            vec![Gen::set_ctl(depth, "\"fail\"".into()), Gen::set_error(depth, format!("toJson({{\"Error\": {}, \"Cause\": {cause}}})", q(error))), Gen::go("false")],
        )
    }

    /// A statement's template, and whether the statement can stop the flow, which its output
    /// `go` then says.
    fn stmt(&mut self, s: &TStmt, depth: usize) -> Option<(String, bool)> {
        let site = s.site;
        match &s.kind {
            TK::Pass => None,
            TK::Assign { name, expr } => {
                let v = format!("toJson({})", self.ex(expr));
                Some((self.compute(&format!("s{site}-let"), depth, &[], vec![("value".into(), Some(self.var_global(name)), v)]), false))
            }
            TK::Break => Some((self.compute(&format!("s{site}-break"), depth, &[], vec![Gen::set_ctl(depth, "\"break\"".into()), Gen::go("false")]), true)),
            TK::Succeed { fields } => {
                let out = if fields.is_empty() { "\"null\"".to_string() } else { format!("toJson({{{}}})", fields.iter().map(|(f, e)| format!("{}: {}", q(f), self.ex(e))).collect::<Vec<_>>().join(", ")) };
                Some((
                    self.compute(&format!("s{site}-succeed"), depth, &[], vec![("output".into(), Some("dd_output".into()), out), Gen::set_ctl(depth, "\"succeed\"".into()), Gen::go("false")]),
                    true,
                ))
            }
            TK::Fail { error, cause, .. } => {
                let c = cause.as_ref().map(|c| self.ex(c)).unwrap_or_else(|| "nil".into());
                Some((self.fail_with(&format!("s{site}-fail"), depth, error, c), true))
            }
            TK::Wait { seconds } => {
                let n = self.name(&format!("s{site}-wait"));
                self.templates.push(json!({ "name": n, "inputs": Gen::inputs(depth, &[]), "suspend": { "duration": seconds.to_string() } }));
                Some((n, false))
            }
            TK::WaitUntil { at } => {
                // the seconds to wait, from the clock as the statement starts; Argo would read a
                // `now()` in the duration again each time it looks
                let secs = format!("int((date({}) - now()).Seconds())", self.ex(at));
                let until = self.compute(&format!("s{site}-until"), depth, &[], vec![("seconds".into(), None, format!("string({secs} > 0 ? {secs} : 0)"))]);
                let wait = self.name(&format!("s{site}-sleep"));
                self.templates.push(json!({ "name": wait, "inputs": { "parameters": [{ "name": "seconds" }] }, "suspend": { "duration": "{{inputs.parameters.seconds}}" } }));
                let n = self.name(&format!("s{site}-wait-until"));
                self.templates.push(json!({
                    "name": n,
                    "inputs": Gen::inputs(depth, &[]),
                    "steps": [
                        [Gen::step("until", &until, Gen::pass(depth), None)],
                        [Gen::step("wait", &wait, vec![json!({ "name": "seconds", "value": "{{steps.until.outputs.parameters.seconds}}" })], None)],
                    ],
                }));
                Some((n, false))
            }
            TK::Match { expr, arms } => Some((self.matching(s, expr, arms, depth), true)),
            TK::Repeat { times, body } => Some((self.repeat(s, *times, body, depth), true)),
            TK::For { var, list, max, parallel: None, body, result, .. } => Some((self.for_loop(s, var, list, *max, body, result.as_ref(), depth), true)),
            TK::For { var, list, max, parallel: Some(k), body, result, locals } => Some((self.parallel_for(s, var, list, *max, *k, body, result.as_ref(), locals, depth), true)),
            TK::Call { target, callee, args, handlers } => Some((self.call(s, target.as_ref(), callee, args, handlers, depth), true)),
        }
    }

    fn matching(&mut self, s: &TStmt, expr: &TExpr, arms: &[TArm], depth: usize) -> String {
        let site = s.site;
        let m = self.m;
        // a case's state reads as none when the case has not started
        let x = match expr {
            TExpr::Var { name, fields, .. } if m.case_index(name).is_some() => {
                let c = format!("sprig.fromJson({})", self.var_raw(name));
                let mut f = c.clone();
                for fl in fields {
                    f = format!("{f}[{}]", q(fl));
                }
                format!("({c} == nil ? nil : {f})")
            }
            other => self.ex(other),
        };
        let mut conds: Vec<String> = Vec::new();
        for a in arms {
            let mut parts = Vec::new();
            if a.none {
                parts.push(format!("{x} == nil"));
            }
            if a.some.is_some() {
                parts.push(format!("{x} != nil"));
            }
            if !a.values.is_empty() {
                if expr.ty().inner() == &Ty::Bool {
                    for v in &a.values {
                        parts.push(format!("{x} == {v}"));
                    }
                } else {
                    parts.push(format!("{x} in [{}]", a.values.iter().map(|v| q(v)).collect::<Vec<_>>().join(", ")));
                }
            }
            conds.push(format!("({})", parts.join(" || ")));
        }
        // the first arm that takes the value: `a<i>`, or `none`
        let mut pick = "\"none\"".to_string();
        for (i, c) in conds.iter().enumerate().rev() {
            pick = format!("{c} ? \"a{i}\" : ({pick})");
        }
        let mut outs: Vec<Out> = vec![("arm".into(), None, pick.clone())];
        // an arm with `some v` sets v to the value
        let mut named: Vec<(String, Vec<usize>)> = Vec::new();
        for (i, a) in arms.iter().enumerate() {
            if let Some(v) = &a.some {
                match named.iter_mut().find(|(n, _)| n == v) {
                    Some((_, is)) => is.push(i),
                    None => named.push((v.clone(), vec![i])),
                }
            }
        }
        for (k, (v, is)) in named.iter().enumerate() {
            let which = is.iter().map(|i| format!("\"a{i}\"")).collect::<Vec<_>>().join(", ");
            outs.push((format!("some{k}"), Some(self.var_global(v)), format!("({pick}) in [{which}] ? toJson({x}) : {}", self.var_raw(v))));
        }
        let pick_t = self.compute(&format!("s{site}-pick"), depth, &[], outs);
        let mut group: Vec<Value> = Vec::new();
        for (i, a) in arms.iter().enumerate() {
            let body = self.block(&a.body, depth, &format!("s{site}-arm{i}"));
            group.push(Gen::step(&format!("arm{i}"), &body, Gen::pass(depth), Some(format!("{{{{steps.pick.outputs.parameters.arm}}}} == a{i}"))));
        }
        let none = self.fail_with(&format!("s{site}-no-arm"), depth, "Dandori.UnexpectedValue", q(&format!("line {}: {} took a value that no arm names", s.line, expr.show())));
        group.push(Gen::step("no-arm", &none, Gen::pass(depth), Some("{{steps.pick.outputs.parameters.arm}} == none".into())));
        let mut go = "\"false\"".to_string();
        for i in (0..arms.len()).rev() {
            go = format!("steps.pick.outputs.parameters.arm == \"a{i}\" ? steps.arm{i}.outputs.parameters.go : ({go})");
        }
        let n = self.name(&format!("s{site}-match"));
        self.templates.push(json!({
            "name": n,
            "inputs": Gen::inputs(depth, &[]),
            "steps": [[Gen::step("pick", &pick_t, Gen::pass(depth), None)], group],
            "outputs": { "parameters": [Gen::go_expr(go)] },
        }));
        n
    }

    /// A round of a loop whose rounds run one at a time: it runs while the flow goes on (a
    /// `break` stops the rounds after it), with the loop's name set to its item, and adds what
    /// it yields to the list.
    fn sequential_round(&mut self, site: usize, depth: usize, body: &[TStmt], item: Option<&str>, yielded: Option<&TExpr>) -> String {
        let ctl = Gen::ctl(depth);
        let mut start: Vec<Out> = vec![Gen::go(&format!("{ctl} == \"next\""))];
        if let Some(var) = item {
            let items = Gen::global_ref(&format!("dd_items_{site}"), depth);
            start.push(("value".into(), Some(self.var_global(var)), format!("{ctl} == \"next\" ? toJson(sprig.fromJson({items})[int(inputs.parameters.i)]) : {}", self.var_raw(var))));
        }
        let start = self.compute(&format!("s{site}-start"), depth, &["i"], start);
        let b = self.block(body, depth, &format!("s{site}-body"));
        let mut steps = vec![
            json!([Gen::step("start", &start, Gen::pass_with(depth, &["i"]), None)]),
            json!([Gen::step("body", &b, Gen::pass(depth), Some("{{steps.start.outputs.parameters.go}}".into()))]),
        ];
        if let Some(y) = yielded {
            let base = format!("dd_out_{site}");
            let out = Gen::global_ref(&base, depth);
            let add = self.compute(&format!("s{site}-yield"), depth, &[], vec![("out".into(), Some(Gen::global_name(&base, depth)), format!("toJson(sprig.append(sprig.fromJson({out}), {}))", self.ex(y)))]);
            steps.push(json!([Gen::step("yield", &add, Gen::pass(depth), Some("{{steps.body.outputs.parameters.go}}".into()))]));
        }
        let n = self.name(&format!("s{site}-round"));
        self.templates.push(json!({ "name": n, "inputs": Gen::inputs(depth, &["i"]), "steps": steps }));
        n
    }

    /// The step that runs a loop's rounds: `count` of them, each with its index as `i` and in
    /// the key's rounds.
    fn rounds_step(round: &str, depth: usize, count: String, extra: Vec<Value>) -> Value {
        let mut args = Gen::pass(depth);
        args[0] = json!({ "name": "rounds", "value": "{{inputs.parameters.rounds}}/{{item}}" });
        args.extend(extra);
        args.push(json!({ "name": "i", "value": "{{item}}" }));
        let mut r = Gen::step("round", round, args, None);
        r["withSequence"] = json!({ "count": count });
        r
    }

    /// After the rounds of a loop whose rounds run one at a time: a `break` has done its work.
    fn loop_done(&mut self, site: usize, depth: usize, result: Option<&(String, TExpr)>) -> String {
        let ctl = Gen::ctl(depth);
        let went = format!("{ctl} in [\"next\", \"break\"]");
        let mut outs = vec![Gen::set_ctl(depth, format!("{ctl} == \"break\" ? \"next\" : {ctl}")), Gen::go(&went)];
        if let Some((rv, _)) = result {
            outs.push(("value".into(), Some(self.var_global(rv)), format!("{went} ? {} : {}", Gen::global_ref(&format!("dd_out_{site}"), depth), self.var_raw(rv))));
        }
        self.compute(&format!("s{site}-done"), depth, &[], outs)
    }

    fn repeat(&mut self, s: &TStmt, times: u32, body: &[TStmt], depth: usize) -> String {
        let site = s.site;
        let round = self.sequential_round(site, depth, body, None, None);
        let done = self.loop_done(site, depth, None);
        let n = self.name(&format!("s{site}-repeat"));
        self.templates.push(json!({
            "name": n,
            "inputs": Gen::inputs(depth, &[]),
            "parallelism": 1,
            "steps": [[Gen::rounds_step(&round, depth, times.to_string(), vec![])], [Gen::step("done", &done, Gen::pass(depth), None)]],
            "outputs": { "parameters": [Gen::go_from("done")] },
        }));
        n
    }

    /// The list of a `for`, its length against the bound, and the number of rounds.
    fn take(&mut self, s: &TStmt, list: &TExpr, max: u32, depth: usize, yields: bool) -> String {
        let site = s.site;
        let l = self.ex(list);
        let over = format!("len({l}) > {max}");
        let mut outs = vec![
            ("items".to_string(), Some(Gen::global_name(&format!("dd_items_{site}"), depth)), format!("toJson({l})")),
            ("count".to_string(), None, format!("{over} ? \"0\" : string(len({l}))")),
            Gen::set_ctl(depth, format!("{over} ? \"fail\" : {}", Gen::ctl(depth))),
            Gen::set_error(
                depth,
                format!(
                    "{over} ? toJson({{\"Error\": \"Dandori.TooManyItems\", \"Cause\": {}}}) : {}",
                    q(&format!("line {}: the list has more than {max} items", s.line)),
                    Gen::global_ref("dd_error", depth)
                ),
            ),
        ];
        if yields {
            outs.push(("out".to_string(), Some(Gen::global_name(&format!("dd_out_{site}"), depth)), "\"[]\"".into()));
        }
        self.compute(&format!("s{site}-take"), depth, &[], outs)
    }

    #[allow(clippy::too_many_arguments)]
    fn for_loop(&mut self, s: &TStmt, var: &str, list: &TExpr, max: u32, body: &[TStmt], result: Option<&(String, TExpr)>, depth: usize) -> String {
        let site = s.site;
        let take = self.take(s, list, max, depth, result.is_some());
        let round = self.sequential_round(site, depth, body, Some(var), result.map(|(_, y)| y));
        let done = self.loop_done(site, depth, result);
        let n = self.name(&format!("s{site}-for"));
        self.templates.push(json!({
            "name": n,
            "inputs": Gen::inputs(depth, &[]),
            "parallelism": 1,
            "steps": [
                [Gen::step("take", &take, Gen::pass(depth), None)],
                [Gen::rounds_step(&round, depth, "{{steps.take.outputs.parameters.count}}".into(), vec![])],
                [Gen::step("done", &done, Gen::pass(depth), None)],
            ],
            "outputs": { "parameters": [Gen::go_from("done")] },
        }));
        n
    }

    /// `for … in parallel`: the rounds run at the same time, each with its own control, error
    /// and variables, and say how they ended; after them, the first failure in the list's
    /// order is the loop's, or the list of what they yielded is its result.
    #[allow(clippy::too_many_arguments)]
    fn parallel_for(&mut self, s: &TStmt, var: &str, list: &TExpr, max: u32, k: u32, body: &[TStmt], result: Option<&(String, TExpr)>, locals: &[String], depth: usize) -> String {
        let site = s.site;
        let inner = depth + 1;
        let take = self.take(s, list, max, depth, false);
        let items = Gen::global_ref(&format!("dd_items_{site}"), depth);
        // a round starts with its own control, error and variables
        let mut start = vec![Gen::set_ctl(inner, "\"next\"".into()), Gen::set_error(inner, "\"null\"".into())];
        for l in locals {
            let v = if l == var { format!("toJson(sprig.fromJson({items})[int(inputs.parameters.i)])") } else { "\"null\"".into() };
            start.push((format!("v{}", self.var_ix[l]), Some(self.var_global(l)), v));
        }
        let start = self.compute(&format!("s{site}-start"), inner, &["i"], start);
        let b = self.block(body, inner, &format!("s{site}-body"));
        let rctl = Gen::ctl(inner);
        let rerr = Gen::global_ref("dd_error", inner);
        let y = result.map(|(_, y)| self.ex(y)).unwrap_or_else(|| "nil".into());
        let end = self.compute(
            &format!("s{site}-end"),
            inner,
            &[],
            vec![(
                "end".into(),
                None,
                format!("toJson({rctl} in [\"fail\", \"task\"] ? {{\"fail\": {{\"Error\": sprig.fromJson({rerr}).Error, \"Cause\": sprig.fromJson({rerr}).Cause, \"task\": {rctl} == \"task\"}}}} : {{\"ok\": {y}}})"),
            )],
        );
        let round = self.name(&format!("s{site}-round"));
        self.templates.push(json!({
            "name": round,
            "inputs": Gen::inputs(inner, &["i"]),
            "steps": [
                [Gen::step("start", &start, Gen::pass_with(inner, &["i"]), None)],
                [Gen::step("body", &b, Gen::pass(inner), None)],
                [Gen::step("end", &end, Gen::pass(inner), None)],
            ],
            "outputs": { "parameters": [{ "name": "end", "valueFrom": { "parameter": "{{steps.end.outputs.parameters.end}}" } }] },
        }));
        // the rounds, and how each ended in the list's order ([] when there are none)
        let outer = if depth == 0 { String::new() } else { format!("{{{{inputs.parameters.s{depth}}}}}") };
        let suffix = json!({ "name": format!("s{inner}"), "value": format!("{outer}_p{site}i{{{{item}}}}") });
        let rounds = self.name(&format!("s{site}-rounds"));
        let mut t = json!({
            "name": rounds,
            "inputs": Gen::inputs(depth, &["count"]),
            "steps": [[Gen::rounds_step(&round, depth, "{{inputs.parameters.count}}".into(), vec![suffix])]],
            "outputs": { "parameters": [{ "name": "ends", "valueFrom": { "parameter": "{{steps.round.outputs.parameters.end}}", "default": "[]" } }] },
        });
        if k > 0 {
            t["parallelism"] = json!(k);
        }
        self.templates.push(t);
        let ends = "sprig.fromJson(inputs.parameters.ends)";
        let first = format!("filter({ends}, {{\"fail\" in #}})[0].fail");
        let failed = format!("len(filter({ends}, {{\"fail\" in #}})) > 0");
        let ctl = Gen::ctl(depth);
        let went = format!("!({failed}) && {ctl} == \"next\"");
        let mut settle = vec![
            Gen::set_ctl(depth, format!("{failed} ? ({first}.task ? \"task\" : \"fail\") : {ctl}")),
            Gen::set_error(depth, format!("{failed} ? toJson({{\"Error\": {first}.Error, \"Cause\": {first}.Cause}}) : {}", Gen::global_ref("dd_error", depth))),
            Gen::go(&went),
        ];
        if let Some((rv, _)) = result {
            settle.push(("value".into(), Some(self.var_global(rv)), format!("{went} ? toJson(map({ends}, {{#.ok}})) : {}", self.var_raw(rv))));
        }
        let settle = self.compute(&format!("s{site}-settle"), depth, &["ends"], settle);
        let mut rounds_args = Gen::pass(depth);
        rounds_args.push(json!({ "name": "count", "value": "{{steps.take.outputs.parameters.count}}" }));
        let mut settle_args = Gen::pass(depth);
        settle_args.push(json!({ "name": "ends", "value": "{{steps.rounds.outputs.parameters.ends}}" }));
        let n = self.name(&format!("s{site}-for"));
        self.templates.push(json!({
            "name": n,
            "inputs": Gen::inputs(depth, &[]),
            "steps": [
                [Gen::step("take", &take, Gen::pass(depth), None)],
                [Gen::step("rounds", &rounds, rounds_args, None)],
                [Gen::step("settle", &settle, settle_args, None)],
            ],
            "outputs": { "parameters": [Gen::go_from("settle")] },
        }));
        n
    }

    /// The template that runs a task or a rule, made once for all its calls.
    fn callee_template(&mut self, callee: &Callee) -> String {
        let m = self.m;
        match callee {
            Callee::Rule(r) => {
                let ru = &m.rules[*r];
                let n = format!("rule-{}", r);
                if self.made.insert(n.clone()) {
                    self.used.insert(n.clone());
                    let mut t = container(&n, "{{workflow.parameters.dandori-caller}}", Some(vec!["node".into(), "/app/call.ts".into(), render::rule_activity(&ru.name)]), &ru.name, None);
                    // a rule is retried on its failures, as on the other platforms
                    t["retryStrategy"] = json!({
                        "limit": crate::check::RULE_RETRIES.to_string(),
                        "retryPolicy": "Always",
                        "backoff": { "duration": format!("{}s", crate::asl::RULE_RETRY_INTERVAL), "factor": fmt_num(crate::asl::RULE_RETRY_BACKOFF) },
                    });
                    self.templates.push(t);
                }
                n
            }
            Callee::Task(ti) => {
                let task = &m.tasks[*ti];
                let n = format!("task-{ti}");
                if self.made.insert(n.clone()) {
                    self.used.insert(n.clone());
                    let timeout = if task.callback { None } else { task.timeout };
                    let mut t = match task.via(Platform::Argo) {
                        Some(Via::Image(img)) => container(&n, img, None, &task.name, timeout),
                        Some(Via::ArgoTemplate(wt)) => child(&n, wt, timeout),
                        _ => container(&n, "{{workflow.parameters.dandori-caller}}", Some(vec!["node".into(), "/app/call.ts".into(), ident(&task.name)]), &task.name, timeout),
                    };
                    if let Some(r) = &task.retry {
                        t["retryStrategy"] = retry(task, r);
                    }
                    self.templates.push(t);
                    if task.callback {
                        let w = format!("{n}-wait");
                        self.used.insert(w.clone());
                        self.templates.push(json!({
                            "name": w,
                            "inputs": { "parameters": [{ "name": "callback_id" }] },
                            "suspend": { "duration": task.timeout.unwrap_or(86_400).to_string() },
                            "outputs": { "parameters": [{ "name": "answer", "valueFrom": { "supplied": {}, "default": TIMEOUT } }] },
                        }));
                    }
                }
                n
            }
        }
    }

    fn call(&mut self, s: &TStmt, target: Option<&Target>, callee: &Callee, args: &[(String, TExpr)], handlers: &[THandler], depth: usize) -> String {
        let m = self.m;
        let site = s.site;
        let (cname, declared, result_ty, callback, starts) = match callee {
            Callee::Task(t) => {
                let task = &m.tasks[*t];
                (task.name.clone(), task.errors.iter().map(|e| e.name.clone()).collect::<Vec<_>>(), task.result.clone(), task.callback, matches!(task.via(Platform::Argo), Some(Via::ArgoTemplate(_))))
            }
            Callee::Rule(r) => (m.rules[*r].name.clone(), vec![], Some(Ty::Record(m.rules[*r].outputs)), false, false),
        };
        // the call as it goes out, with its key and the id of its callback
        let key = format!("inputs.parameters.wf + \"/{site}\" + inputs.parameters.rounds");
        let mut fields: Vec<String> = args.iter().map(|(a, e)| format!("{}: {}", q(a), self.ex(e))).collect();
        if let Callee::Task(t) = callee {
            if m.tasks[*t].key {
                fields.push(format!("\"idempotency_key\": {key}"));
            }
        }
        let cb = format!("{key} + \"/1\"");
        if callback {
            fields.push(format!("\"callback_id\": {cb}"));
        }
        let mut prep: Vec<Out> = vec![("call".into(), None, format!("toJson({{{}}})", fields.join(", ")))];
        if callback {
            prep.push(("callback".into(), None, cb));
        }
        let prep = self.compute(&format!("s{site}-args"), depth, &["wf"], prep);
        let mut prep_args = Gen::pass(depth);
        prep_args.push(json!({ "name": "wf", "value": "{{workflow.name}}" }));
        let tmpl = self.callee_template(callee);
        let mut group = vec![
            json!([Gen::step("args", &prep, prep_args, None)]),
            json!([{
                "name": "try",
                "template": tmpl,
                "arguments": { "parameters": [{ "name": "call", "value": "{{steps.args.outputs.parameters.call}}" }] },
                "continueOn": { "failed": true, "error": true },
            }]),
        ];
        if callback {
            group.push(json!([{
                "name": "wait",
                "template": format!("{tmpl}-wait"),
                "arguments": { "parameters": [{ "name": "callback_id", "value": "{{steps.args.outputs.parameters.callback}}" }] },
                "when": "{{steps.try.status}} == Succeeded",
            }]));
        }
        // how the call came out, bound once at the head of each output's expression: the kind of
        // the error ("ok" when there is none), the answer, its checks, and the handler that takes it
        let decl = format!("[{}]", declared.iter().map(|d| q(d)).collect::<Vec<_>>().join(", "));
        let mut pre = String::from("let killed = inputs.parameters.code in [\"143\", \"137\"]; let e = inputs.parameters.error != \"null\" ? sprig.fromJson(inputs.parameters.error) : nil; ");
        let cause = if callback {
            pre.push_str(&format!("let w = inputs.parameters.waited; let wv = w != \"\" && w != {t} ? sprig.fromJson(w) : nil; ", t = q(TIMEOUT)));
            pre.push_str(&format!(
                "let k = inputs.parameters.status != \"Succeeded\" ? (killed ? \"timeout\" : \"failure\") : (w == {t} ? \"timeout\" : (\"error\" in wv ? (wv.error in {decl} ? wv.error : \"failure\") : \"ok\")); ",
                t = q(TIMEOUT)
            ));
            pre.push_str("let a = k == \"ok\" ? wv.ok : nil; ");
            format!("w == {} ? \"no answer in time\" : (wv != nil ? (wv.message ?? \"\") : (killed ? \"ran past its timeout\" : (e != nil ? (e.message ?? \"\") : \"\")))", q(TIMEOUT))
        } else {
            pre.push_str(&format!("let k = inputs.parameters.status == \"Succeeded\" ? \"ok\" : (inputs.parameters.code == \"3\" && e != nil && e.error in {decl} ? e.error : (killed ? \"timeout\" : \"failure\")); "));
            pre.push_str("let a = k == \"ok\" ? sprig.fromJson(inputs.parameters.answer) : nil; ");
            "killed ? \"ran past its timeout\" : (e != nil ? (e.message ?? \"\") : \"\")".to_string()
        };
        // the answer's checks: its type, and for a case the states it may carry
        let (typed, stated) = match (target, &result_ty) {
            (Some(tg), Some(ty)) => {
                let stated = match (tg, m.monitors.get(&site)) {
                    (Target::Case(c), Some((_, allowed))) => format!("a[{}] in [{}]", q(&m.cases[*c].state_field), allowed.iter().map(|x| q(x)).collect::<Vec<_>>().join(", ")),
                    _ => "true".into(),
                };
                (self.check("a", ty), stated)
            }
            _ => ("true".into(), "true".into()),
        };
        pre.push_str(&format!("let typed = k == \"ok\" && {typed}; let ok = typed && {stated}; "));
        // the first handler that takes the error: `h<i>`, or `none`
        let mut handler = "\"none\"".to_string();
        for (i, h) in handlers.iter().enumerate().rev() {
            let takes = if h.errors.contains(&HErr::Failure) {
                "true".to_string()
            } else {
                let names: Vec<String> = h
                    .errors
                    .iter()
                    .map(|e| match e {
                        HErr::Timeout => q("timeout"),
                        HErr::Declared(n) => q(n),
                        HErr::Failure => unreachable!(),
                    })
                    .collect();
                format!("k in [{}]", names.join(", "))
            };
            handler = format!("{takes} ? \"h{i}\" : ({handler})");
        }
        pre.push_str(&format!("let h = k == \"ok\" ? \"none\" : ({handler}); let on = ok || h != \"none\"; "));
        let states_msg = match (target, m.monitors.get(&site)) {
            (Some(Target::Case(_)), Some((_, allowed))) => format!("line {}: {} answered with a state the machine does not lead to here (expected one of {})", s.line, cname, allowed.join(", ")),
            _ => String::new(),
        };
        let bad_msg = format!("line {}: the answer from {} does not have the declared shape", s.line, cname);
        let err = Gen::global_ref("dd_error", depth);
        let mut outs: Vec<Out> = vec![
            ("handler".into(), None, format!("{pre}h")),
            Gen::set_ctl(depth, format!("{pre}on ? \"next\" : (k == \"ok\" ? \"fail\" : \"task\")")),
            Gen::set_error(
                depth,
                format!(
                    "{pre}on ? {err} : (k == \"ok\" ? (typed ? toJson({{\"Error\": \"Dandori.UnexpectedState\", \"Cause\": {}}}) : toJson({{\"Error\": \"Dandori.BadResponse\", \"Cause\": {}}})) : toJson({{\"Error\": k, \"Cause\": {cause}}}))",
                    q(&states_msg),
                    q(&bad_msg)
                ),
            ),
            ("go".into(), None, format!("{pre}ok ? \"true\" : \"false\"")),
        ];
        let var = match target {
            Some(Target::Let(v)) => Some(v.clone()),
            Some(Target::Case(c)) => Some(m.cases[*c].name.clone()),
            None => None,
        };
        if let (Some(v), Some(_)) = (&var, &result_ty) {
            // the answer as it came, not as it reads back, so that a number keeps its digits
            let value = if callback { "toJson(a)" } else { "inputs.parameters.answer" };
            outs.push(("value".into(), Some(self.var_global(v)), format!("{pre}ok ? {value} : {}", self.var_raw(v))));
        }
        let after = self.compute(&format!("s{site}-after"), depth, &["status", "code", "answer", "error", "waited"], outs);
        // what the try left, read so that a value that is not there reads as a default
        let mut after_args = Gen::pass(depth);
        after_args.push(json!({ "name": "status", "value": "{{steps.try.status}}" }));
        after_args.push(json!({ "name": "code", "value": "{{=steps.try.exitCode ?? \"\"}}" }));
        after_args.push(json!({ "name": "answer", "value": "{{=steps.try.status == \"Succeeded\" ? (steps.try.outputs.parameters.answer ?? \"null\") : \"null\"}}" }));
        after_args.push(json!({
            "name": "error",
            "value": if starts { "null" } else { "{{=steps.try.status == \"Failed\" ? (steps.try.outputs.parameters.error ?? \"null\") : \"null\"}}" },
        }));
        after_args.push(json!({
            "name": "waited",
            "value": if callback { "{{=steps.wait.status == \"Succeeded\" ? (steps.wait.outputs.parameters.answer ?? \"\") : \"\"}}" } else { "" },
        }));
        group.push(json!([Gen::step("after", &after, after_args, None)]));
        let mut hs: Vec<Value> = Vec::new();
        let mut go = "steps.after.outputs.parameters.go".to_string();
        for (i, h) in handlers.iter().enumerate().rev() {
            go = format!("steps.after.outputs.parameters.handler == \"h{i}\" ? steps.on{i}.outputs.parameters.go : ({go})");
            let b = self.block(&h.body, depth, &format!("s{site}-on{i}"));
            hs.insert(0, Gen::step(&format!("on{i}"), &b, Gen::pass(depth), Some(format!("{{{{steps.after.outputs.parameters.handler}}}} == h{i}"))));
        }
        if !hs.is_empty() {
            group.push(Value::Array(hs));
        }
        let n = self.name(&format!("s{site}-call"));
        self.templates.push(json!({ "name": n, "inputs": Gen::inputs(depth, &[]), "steps": group, "outputs": { "parameters": [Gen::go_expr(go)] } }));
        n
    }

    /// The WorkflowTemplate, and the comment that goes before it in the YAML.
    fn workflow(&mut self) -> (Value, String) {
        let m = self.m;
        // the start: every variable, the inputs from the parameter `input`, checked; an
        // output's expression does not see the workflow's parameters, so the input comes as
        // an argument
        let input = "sprig.fromJson(inputs.parameters.input)";
        let mut checks = vec![format!("type({input}) == \"map\"")];
        for (n, t) in &m.inputs {
            checks.push(self.check(&format!("{input}[{}]", q(n)), t));
        }
        let ok = format!("({})", checks.join(" && "));
        let mut init_out: Vec<Out> = Vec::new();
        for (v, _) in &m.vars {
            if self.var_depth(v) > 0 {
                continue;
            }
            // when the input does not pass the checks, the flow does not run and the values go unread
            let val = if m.inputs.iter().any(|(i, _)| i == v) { format!("type({input}) == \"map\" ? toJson({input}[{}]) : \"null\"", q(v)) } else { "\"null\"".into() };
            init_out.push((format!("v{}", self.var_ix[v]), Some(self.var_global(v)), val));
        }
        init_out.push(Gen::set_ctl(0, format!("{ok} ? \"next\" : \"fail\"")));
        init_out.push(Gen::set_error(0, format!("{ok} ? \"null\" : toJson({{\"Error\": \"Dandori.BadInput\", \"Cause\": \"the execution's input does not have the declared shape\"}})")));
        init_out.push(("output".into(), Some("dd_output".into()), "\"null\"".into()));
        init_out.push(Gen::go(&ok));
        let init = self.compute("dd-init", 0, &["input"], init_out);
        let flow = self.block(&m.flow, 0, "flow");
        let top = |args: Vec<Value>| -> Vec<Value> {
            let mut a = vec![json!({ "name": "rounds", "value": "" })];
            a.extend(args);
            a
        };
        let mut main = vec![
            json!([Gen::step("init", &init, top(vec![json!({ "name": "input", "value": "{{workflow.parameters.input}}" })]), None)]),
            json!([Gen::step("flow", &flow, top(vec![]), Some("{{steps.init.outputs.parameters.go}}".into()))]),
        ];
        let ctl = Gen::ctl(0);
        if let Some(block) = &m.on_failure {
            // a task's error that nothing handled: `on failure`, and then the run fails with it
            let check = self.compute("dd-check", 0, &[], vec![("task".into(), None, format!("{ctl} == \"task\" ? \"true\" : \"false\""))]);
            let begin = self.compute("dd-recover-begin", 0, &[], vec![Gen::set_ctl(0, "\"next\"".into())]);
            let b = self.block(block, 0, "on-failure");
            let again = self.compute("dd-recover-end", 0, &[], vec![Gen::set_ctl(0, format!("{ctl} == \"next\" ? \"task\" : {ctl}"))]);
            self.templates.push(json!({
                "name": "dd-recover",
                "inputs": Gen::inputs(0, &[]),
                "steps": [[Gen::step("begin", &begin, Gen::pass(0), None)], [Gen::step("block", &b, Gen::pass(0), None)], [Gen::step("end", &again, Gen::pass(0), None)]],
            }));
            main.push(json!([Gen::step("check", &check, top(vec![]), None)]));
            main.push(json!([Gen::step("on-failure", "dd-recover", top(vec![]), Some("{{steps.check.outputs.parameters.task}}".into()))]));
        }
        let err = format!("sprig.fromJson({})", Gen::global_ref("dd_error", 0));
        let finish = self.compute(
            "dd-finish",
            0,
            &[],
            vec![
                ("failed".into(), None, format!("{ctl} in [\"fail\", \"task\"] ? \"true\" : \"false\"")),
                ("message".into(), None, format!("{ctl} in [\"fail\", \"task\"] ? {err}.Error + \": \" + (type({err}.Cause) == \"string\" ? {err}.Cause : toJson({err}.Cause)) : \"\"")),
            ],
        );
        main.push(json!([Gen::step("finish", &finish, top(vec![]), None)]));
        main.push(json!([Gen::step("end", "dd-end", vec![json!({ "name": "message", "value": "{{steps.finish.outputs.parameters.message}}" })], Some("{{steps.finish.outputs.parameters.failed}}".into()))]));
        let mut templates = vec![json!({ "name": "main", "steps": main })];
        templates.push(json!({
            "name": "dd-end",
            "inputs": { "parameters": [{ "name": "message" }] },
            "container": {
                "image": "{{workflow.parameters.dandori-shell}}",
                "command": ["sh", "-c", "printf '%s' \"$DD_ERROR\" > /dev/termination-log; echo \"$DD_ERROR\" >&2; exit 1"],
                "env": [{ "name": "DD_ERROR", "value": "{{inputs.parameters.message}}" }],
            },
        }));
        templates.push(json!({ "name": "dd-nothing", "container": { "image": "{{workflow.parameters.dandori-shell}}", "command": ["true"] } }));
        templates.extend(std::mem::take(&mut self.templates));

        let name = workflow_name(m);
        let mut annotations = Map::new();
        if !m.description.is_empty() {
            annotations.insert("workflows.argoproj.io/description".into(), json!(m.description));
        }
        let doc = json!({
            "apiVersion": "argoproj.io/v1alpha1",
            "kind": "WorkflowTemplate",
            "metadata": { "name": name, "annotations": annotations },
            "spec": {
                "entrypoint": "main",
                "arguments": { "parameters": [
                    { "name": "input", "value": "{}" },
                    { "name": "dandori-caller", "value": format!("dandori-caller-{name}:v{}", m.version) },
                    { "name": "dandori-shell", "value": "busybox:1.37" },
                ] },
                "templates": templates,
            },
        });
        let mut out = String::new();
        out.push_str(&format!("# Code generated by dandori from {}. DO NOT EDIT.\n", m.source_file));
        out.push_str(&format!("# {} v{}{}\n#\n", m.name, m.version, if m.description.is_empty() { String::new() } else { format!(": {}", m.description) }));
        out.push_str("# Submit with the input as JSON: argo submit --from workflowtemplate/<name> -p input='{…}'.\n");
        out.push_str("# The outputs end up in the global parameter dd_output; a failure's error and cause in dd_error.\n#\n");
        out.push_str("# The variables, as global parameters (JSON):\n");
        for (v, _) in &m.vars {
            out.push_str(&format!("#   {} = {v}\n", self.var_base(v)));
        }
        let own: Vec<&TaskDef> = m.tasks.iter().filter(|t| matches!(t.via(Platform::Argo), Some(Via::Image(_)))).collect();
        if !own.is_empty() {
            out.push_str("#\n# A task with `image` runs in a container of that image. The call comes in DANDORI_CALL as JSON\n");
            out.push_str("# (with `idempotency_key` and `callback_id` when the task has them). Write the answer as JSON to\n");
            out.push_str("# /tmp/dandori/answer.json and exit 0; for a declared error, write { \"error\": <name>, \"message\": … }\n");
            out.push_str("# to /tmp/dandori/error.json and exit 3. A pod stopped at its `timeout` is a timeout; any other exit is a failure.\n");
        }
        if m.tasks.iter().any(|t| t.callback) {
            out.push_str("#\n# A callback's answer: argo node set <workflow> --output-parameter answer='{\"ok\": …}' (or\n");
            out.push_str("# '{\"error\": <name>, \"message\": …}') --node-field-selector inputs.parameters.callback_id.value=<callback_id>,\n");
            out.push_str("# then argo resume <workflow> with the same selector. <workflow> is the id up to its first `/`.\n");
        }
        if m.tasks.iter().any(|t| t.argo_template.is_some()) {
            out.push_str("#\n# A task with `workflow template` creates a Workflow: the workflow's service account needs to create\n");
            out.push_str("# and watch workflows.argoproj.io, and the template's workflow answers with its global parameter dd_output.\n");
        }
        out.push('\n');
        (doc, out)
    }
}

/// The name of the WorkflowTemplate: the workflow's name when it is ASCII, else a digest of it.
pub fn workflow_name(m: &Model) -> String {
    let s = slug(&m.name);
    if !s.is_empty() && m.name.is_ascii() {
        return s;
    }
    // FNV-1a of the name, so that the same workflow keeps the same name
    let mut h: u64 = 0xcbf29ce484222325;
    for b in m.name.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    format!("dandori-{:08x}", h as u32)
}

fn fmt_num(x: f64) -> String {
    if x.fract() == 0.0 {
        format!("{}", x as i64)
    } else {
        format!("{x}")
    }
}

/// A container that runs a task or a rule by the protocol at the top of this file.
fn container(name: &str, image: &str, command: Option<Vec<String>>, what: &str, timeout: Option<u64>) -> Value {
    let mut c = Map::new();
    c.insert("image".into(), json!(image));
    if let Some(cmd) = command {
        c.insert("command".into(), json!(cmd));
    }
    c.insert(
        "env".into(),
        json!([
            { "name": "DANDORI_CALL", "value": "{{inputs.parameters.call}}" },
            { "name": "DANDORI_WORKFLOW", "value": "{{workflow.name}}" },
            { "name": "DANDORI_TASK", "value": what },
        ]),
    );
    let mut t = json!({
        "name": name,
        "inputs": { "parameters": [{ "name": "call" }] },
        "container": Value::Object(c),
        "outputs": { "parameters": [
            { "name": "answer", "valueFrom": { "path": "/tmp/dandori/answer.json", "default": "null" } },
            { "name": "error", "valueFrom": { "path": "/tmp/dandori/error.json", "default": "null" } },
        ] },
    });
    if let Some(s) = timeout {
        t["activeDeadlineSeconds"] = json!(s);
    }
    t
}

/// A workflow made from a WorkflowTemplate, run to its end; its answer is its `dd_output`.
fn child(name: &str, template: &str, timeout: Option<u64>) -> Value {
    let manifest = format!(
        "apiVersion: argoproj.io/v1alpha1\nkind: Workflow\nmetadata:\n  generateName: {}-\n  labels:\n    dandori-parent: \"{{{{workflow.name}}}}\"\nspec:\n  workflowTemplateRef:\n    name: {}\n  arguments:\n    parameters:\n    - name: input\n      value: {{{{=toJson(inputs.parameters.call)}}}}\n",
        slug(template),
        template
    );
    let mut t = json!({
        "name": name,
        "inputs": { "parameters": [{ "name": "call" }] },
        "resource": {
            "action": "create",
            "successCondition": "status.phase == Succeeded",
            "failureCondition": "status.phase in (Failed, Error)",
            "manifest": manifest,
        },
        "outputs": { "parameters": [
            { "name": "answer", "valueFrom": { "jsonPath": "{.status.outputs.parameters[?(@.name==\"dd_output\")].value}", "default": "null" } },
        ] },
    });
    if let Some(s) = timeout {
        t["activeDeadlineSeconds"] = json!(s);
    }
    t
}

/// `retry` as Argo's retryStrategy: the same number of tries, the same waits between them,
/// and an expression that picks the errors the `.flow` retries by the exit code and the
/// declared error's name, which the container leaves as its termination message.
fn retry(task: &TaskDef, r: &Retry) -> Value {
    let on: Vec<String> = if r.on.is_empty() { vec!["failure".into(), "timeout".into()] } else { r.on.clone() };
    let killed = "(lastRetry.exitCode == \"143\" || lastRetry.exitCode == \"137\")";
    let mut parts: Vec<String> = Vec::new();
    let declared: Vec<&str> = task.errors.iter().map(|e| e.name.as_str()).filter(|n| on.iter().any(|o| o == n)).collect();
    if !declared.is_empty() {
        parts.push(format!(
            "(lastRetry.exitCode == \"3\" && ({}))",
            declared.iter().map(|d| format!("lastRetry.message endsWith {}", q(&format!(": {d}")))).collect::<Vec<_>>().join(" || ")
        ));
    }
    if on.iter().any(|o| o == "timeout") {
        parts.push(killed.into());
    }
    if on.iter().any(|o| o == "failure") {
        parts.push(format!("(lastRetry.exitCode != \"3\" && !{killed})"));
    }
    json!({
        "limit": r.times.to_string(),
        "retryPolicy": "Always",
        "backoff": { "duration": format!("{}s", r.every), "factor": fmt_num(r.backoff) },
        "expression": parts.join(" || "),
    })
}

/// YAML with every string in double quotes (as JSON writes them), so that no value is read as
/// something else (`y` as true, `1.0` as a number).
pub fn yaml(v: &Value, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let key = |k: &str| {
        let plain = k.chars().next().map(|c| c.is_ascii_alphabetic()).unwrap_or(false) && k.chars().all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-');
        if plain {
            k.to_string()
        } else {
            q(k)
        }
    };
    let scalar = |x: &Value| -> Option<String> {
        match x {
            Value::String(s) => Some(q(s)),
            Value::Number(n) => Some(n.to_string()),
            Value::Bool(b) => Some(b.to_string()),
            Value::Null => Some("null".into()),
            Value::Array(a) if a.is_empty() => Some("[]".into()),
            Value::Object(o) if o.is_empty() => Some("{}".into()),
            _ => None,
        }
    };
    let mut out = String::new();
    match v {
        Value::Object(o) => {
            for (k, x) in o {
                match scalar(x) {
                    Some(s) => out.push_str(&format!("{pad}{}: {s}\n", key(k))),
                    None => {
                        out.push_str(&format!("{pad}{}:\n", key(k)));
                        let inner = if matches!(x, Value::Array(_)) { indent } else { indent + 2 };
                        out.push_str(&yaml(x, inner));
                    }
                }
            }
        }
        Value::Array(a) => {
            for x in a {
                match scalar(x) {
                    Some(s) => out.push_str(&format!("{pad}- {s}\n")),
                    None => {
                        let body = yaml(x, indent + 2);
                        // the first line of the item goes after the dash
                        let trimmed = body.trim_start_matches(' ');
                        out.push_str(&format!("{pad}- {trimmed}"));
                    }
                }
            }
        }
        other => out.push_str(&format!("{pad}{}\n", scalar(other).unwrap_or_default())),
    }
    out
}
