//! The workflow as a graph of pydantic-graph (2.x): a Python package whose `graph` runs the
//! flow in the process that calls it. Every statement is a node (`BaseNode`), and the return
//! type of its `run` names the nodes it can go to, so `graph.render()` draws the flow.
//!
//! - `types.py`, `io.py`, `rules.py`: as for Temporal's Python SDK (`temporal_py.rs`), the
//!   rules as plain functions
//! - `tasks.py`: the tasks; `make_tasks(own, transport)`, where a declared error of a task you
//!   write is raised as `TaskFailure(kind, message)`
//! - `runtime.py`: retries, error kinds, keys, the clock and the answers of callbacks
//! - `graph.py`: `State` (the flow's variables), `Deps` (the tasks, the rules, the clock, the
//!   callbacks' answers, the run's id), the nodes, and `graph`
//!
//! A run lives in the process that runs it: pydantic-graph 2.x keeps no state anywhere else,
//! so a run that the process loses is lost. The waits sleep by `Deps.clock`, and a callback's
//! answer comes to `Deps.callbacks` in the same process. A round of `for … in parallel` is a
//! graph of its own, run inside the loop's node on a copy of the state.

use crate::diag::Diag;
use crate::model::*;
use crate::render::{self, ident};
use crate::temporal_py::{method, py_check, py_name, py_type, q, retriers, rules_file, task_doc, task_impl, types_file, IO};
use std::collections::{BTreeMap, BTreeSet};

/// The package the build writes: the workflow's name.
pub fn package(m: &Model) -> String {
    ident(&m.name)
}

/// The End type of the main graph: the workflow's outputs, or None.
const OUTPUT: &str = "dict[str, Any] | None";

/// Where the flow goes from a node: another node, or the end of its graph with a value.
#[derive(Clone, Debug, PartialEq)]
enum Jump {
    Node(String),
    End(String),
}

impl Jump {
    fn code(&self) -> String {
        match self {
            Jump::Node(n) => format!("return {n}()"),
            Jump::End(x) => format!("return End({x})"),
        }
    }
}

/// What a task's error that no `on` takes does.
#[derive(Clone)]
enum Unhandled {
    /// keep it and run `on failure`, whose first node this is
    OnFailure(Jump),
    /// end the run as failed with it
    Fail,
    /// raise it out of the graph: a parallel round's, which the loop's node settles
    Raise,
}

#[derive(Clone)]
struct Ctx {
    /// where `break` goes
    brk: Option<Jump>,
    unhandled: Unhandled,
    /// the End type of the graph the nodes are in
    end: &'static str,
}

struct Node {
    class: String,
    doc: String,
    /// the order in the file: the statement's site, then its place among the statement's nodes
    order: (usize, usize),
    body: Vec<String>,
    targets: Vec<Jump>,
    end: &'static str,
}

impl Node {
    fn line(&mut self, depth: usize, s: &str) {
        self.body.push(if s.is_empty() { String::new() } else { format!("{}{s}", "    ".repeat(depth)) });
    }

    fn jump(&mut self, depth: usize, j: &Jump) {
        self.line(depth, &j.code());
        if !self.targets.contains(j) {
            self.targets.push(j.clone());
        }
    }
}

/// A round's graph: its name, its first node, and its nodes.
struct Round {
    name: String,
    entry: String,
    nodes: Vec<Node>,
}

struct Gen<'a> {
    m: &'a Model,
    nodes: Vec<Node>,
    rounds: Vec<Round>,
    loops: Vec<usize>,
    /// the state's fields besides the variables: name → (type, default)
    fields: BTreeMap<String, (String, String)>,
}

pub fn build(m: &Model) -> Result<Vec<(String, String)>, Vec<Diag>> {
    let dir = package(m);
    let header = format!("# Code generated by dandori from {}. DO NOT EDIT.\n", m.source_file);
    let called: BTreeSet<usize> = m.all_stmts().iter().filter_map(|s| match &s.kind { TK::Call { callee: Callee::Rule(r), .. } => Some(*r), _ => None }).collect();
    let mut g = Gen { m, nodes: Vec::new(), rounds: Vec::new(), loops: Vec::new(), fields: BTreeMap::new() };
    let graph = g.graph(&header, !called.is_empty());
    let mut files = vec![
        (format!("{dir}/__init__.py"), format!("{header}# {} v{}: the workflow as a pydantic-graph graph. See graph.py.\n", m.name, m.version)),
        (format!("{dir}/types.py"), types_file(m, &header)),
        (format!("{dir}/tasks.py"), tasks_file(m, &header)),
        (format!("{dir}/io.py"), format!("{header}{IO}")),
        (format!("{dir}/runtime.py"), format!("{header}{RUNTIME}")),
        (format!("{dir}/graph.py"), graph),
    ];
    if !called.is_empty() {
        files.push((format!("{dir}/rules.py"), rules_file(m, &header, &called, false)));
    }
    Ok(files)
}

/// tasks.py: the tasks the graph calls, the ones the user writes, and the code for the others.
fn tasks_file(m: &Model, header: &str) -> String {
    let p = Platform::Graph;
    let own: Vec<&TaskDef> = m.tasks.iter().filter(|t| matches!(t.via(p), Some(Via::Own))).collect();
    let mut a = header.to_string();
    a.push_str("# The tasks the graph calls.\n#\n");
    a.push_str("# - A task that says `lambda`, `http` or `aws` is written here: it sends what Step Functions\n");
    a.push_str("#   would send, through a Transport (io.py), where the credentials and the clients are yours to set.\n");
    a.push_str("# - So is a task that says `agent`: the model gets the arguments as JSON text, as from Step\n");
    a.push_str("#   Functions, and answers {\"answer\": …} in the JSON Schema below; the Transport runs the agent.\n");
    a.push_str("# - The others are yours to write (OwnTasks). A declared error is raised as\n");
    a.push_str("#   TaskFailure(\"<error>\", \"...\"); any other exception is a failure.\n");
    a.push_str("# - The graph retries by itself, as the `retry` of each task says.\n");
    a.push_str("# - A task with `key` gets `idempotency_key`: pass it on to the other side as it is.\n");
    a.push_str("# - A `callback` task gets `callback_id` and returns once it has handed the id on. The answer comes\n");
    a.push_str("#   when the code that hears it calls `Deps.callbacks.answer(callback_id, {\"ok\": …})` (or\n");
    a.push_str("#   {\"error\": <name>, \"message\": …}) in the process the run is in.\n\n");
    a.push_str("from __future__ import annotations\n\nfrom typing import Any, Protocol\n\n");
    a.push_str("from . import io\nfrom . import types as T\nfrom .runtime import TaskFailure\n\n\n");
    a.push_str(&crate::temporal_py::schemas_block(m, &m.tasks.iter().collect::<Vec<_>>(), p));
    a.push_str("class OwnTasks(Protocol):\n    \"\"\"The tasks you write: the ones that say neither `lambda`, `http`, `aws` nor `agent`.\"\"\"\n");
    if own.is_empty() {
        a.push('\n');
    }
    for task in &own {
        a.push_str(&format!("\n    async def {}(self, args: dict[str, Any]) -> Any:\n        \"\"\"{}\"\"\"\n        ...\n", method(&task.name), task_doc(m, task)));
    }
    a.push_str("\n\ndef fail(kind: str, message: str) -> TaskFailure:\n    return TaskFailure(kind, message)\n\n\n");
    a.push_str("class Tasks:\n    \"\"\"Your tasks and the ones dandori writes: what the graph calls.\"\"\"\n\n");
    a.push_str("    def __init__(self, own: OwnTasks, transport: io.Transport | None = None) -> None:\n        self._own = own\n        self._t = transport if transport is not None else io.transport()\n");
    for task in &m.tasks {
        a.push_str(&format!("\n    async def {}(self, args: dict[str, Any]) -> Any:\n        \"\"\"{}\"\"\"\n", method(&task.name), task_doc(m, task)));
        let lines = task_impl(task, p);
        let uses_own = lines.iter().any(|l| l.contains("own."));
        a.push_str(if uses_own { "        own = self._own\n" } else { "        t = self._t\n" });
        for l in lines {
            a.push_str(&format!("        {l}\n"));
        }
    }
    a.push_str("\n\ndef make_tasks(own: OwnTasks, transport: io.Transport | None = None) -> Tasks:\n    return Tasks(own, transport)\n");
    a
}

const RUNTIME: &str = r#"# What the generated graph shares: retries, error kinds, keys, the clock, and the answers of
# callbacks.

from __future__ import annotations

import asyncio
import itertools
import json
from datetime import datetime, timezone
from typing import Any, Awaitable, Callable, Sequence


class Failure(Exception):
    """The end of a run as failed, with the error's name and its cause: `graph.run` raises it."""

    def __init__(self, error: str, cause: str | None) -> None:
        super().__init__(f"{error}: {cause}" if cause else error)
        self.error = error
        self.cause = cause


class TaskFailure(Exception):
    """A declared error of a task you write: raise TaskFailure("card_declined", "...")."""

    def __init__(self, kind: str, message: str = "") -> None:
        super().__init__(message)
        self.kind = kind
        self.message = message


class TaskError(Exception):
    """A task that failed after its retries, with the kind of error the `.flow` names it by."""

    def __init__(self, kind: str, message: str) -> None:
        super().__init__(message)
        self.kind = kind
        self.message = message


class CallbackTimeout(Exception):
    """A callback that got no answer in time."""

    def __init__(self) -> None:
        super().__init__("no answer in time")
        self.message = "no answer in time"


class CallbackError(Exception):
    """A callback answered with an error."""

    def __init__(self, kind: str, message: str) -> None:
        super().__init__(message)
        self.kind = kind
        self.message = message


def kind_of(e: BaseException, declared: Sequence[str]) -> str:
    """The kind of a task's error: a declared error, "timeout", or "failure"."""
    if isinstance(e, (CallbackTimeout, asyncio.TimeoutError, TimeoutError)):
        return "timeout"
    if isinstance(e, (TaskFailure, CallbackError)):
        return e.kind if e.kind in declared else "failure"
    return "failure"


async def attempt(call: Callable[[], Awaitable[Any]], retriers: Sequence[dict[str, Any]], declared: Sequence[str], clock: Clock) -> Any:
    """Call once, and again as the retriers say, waiting between as Step Functions would."""
    counts = [0] * len(retriers)
    while True:
        try:
            return await call()
        except (Failure, TaskError):
            raise
        except Exception as e:  # noqa: BLE001 - a task can fail any way; the kind says how
            kind = kind_of(e, declared)
            again = False
            for i, r in enumerate(retriers):
                if kind in r["on"] or "*" in r["on"]:
                    if counts[i] < r["max"]:
                        await clock.sleep(r["every"] * r["backoff"] ** counts[i])
                        counts[i] += 1
                        again = True
                    break
            if not again:
                raise TaskError(kind, str(getattr(e, "message", e))) from None


async def within(call: Awaitable[Any], seconds: int | None) -> Any:
    """A task's `timeout`."""
    if seconds is None:
        return await call
    return await asyncio.wait_for(call, seconds)


def key(run_id: str, site: int, rounds: Sequence[int]) -> str:
    """The idempotency key of a call: the run, the call's place, and the round of each loop around it."""
    return "/".join([run_id, str(site), *(str(r) for r in rounds)])


def counter() -> Any:
    """The tries of one call, counted from 1."""
    return itertools.count(1)


def callback_id(run_id: str, site: int, rounds: Sequence[int], n: int) -> str:
    """The id a callback task hands on: which run, and which call it answers."""
    return json.dumps([run_id, "/".join([str(site), *(str(r) for r in rounds), str(n)])], ensure_ascii=False, separators=(",", ":"))


class Clock:
    """The time a run reads and waits by: the real one. A test can give one that skips ahead."""

    def now(self) -> datetime:
        return datetime.now(timezone.utc)

    async def sleep(self, seconds: float) -> None:
        await asyncio.sleep(seconds)


class Callbacks:
    """Where the answers of callbacks come in: the code that hears an answer calls
    `answer(callback_id, {"ok": value})` or `answer(callback_id, {"error": name, "message": text})`
    in the process the run is in."""

    def __init__(self) -> None:
        self._answers: dict[str, dict[str, Any]] = {}
        self._waiting: dict[str, asyncio.Event] = {}

    def answer(self, callback_id: str, answer: dict[str, Any]) -> None:
        self._answers[callback_id] = answer
        waiting = self._waiting.get(callback_id)
        if waiting is not None:
            waiting.set()

    async def wait(self, callback_id: str, seconds: float, clock: Clock) -> dict[str, Any] | None:
        """The answer, or None when `seconds` pass first."""
        if callback_id not in self._answers:
            came = self._waiting.setdefault(callback_id, asyncio.Event())
            got = asyncio.ensure_future(came.wait())
            late = asyncio.ensure_future(clock.sleep(seconds))
            try:
                await asyncio.wait({got, late}, return_when=asyncio.FIRST_COMPLETED)
            finally:
                got.cancel()
                late.cancel()
                self._waiting.pop(callback_id, None)
        return self._answers.pop(callback_id, None)


async def await_callback(callbacks: Callbacks, clock: Clock, id: str, seconds: int) -> Any:
    """Wait for the answer of the callback with this id."""
    a = await callbacks.wait(id, seconds, clock)
    if a is None:
        raise CallbackTimeout()
    if isinstance(a.get("error"), str):
        raise CallbackError(a["error"], a.get("message") or "")
    return a.get("ok")


def at_a_time(k: int) -> int:
    """How many rounds of `for … in parallel` run at a time: all, when the `.flow` does not say (0)."""
    return k


async def rounds(items: Sequence[Any], k: int, round: Callable[[Any, int], Awaitable[Any]]) -> list[Any]:
    """Run a round for every item, `k` at a time (0: all at once). Every round runs to its end;
    then what they yield comes back in the list's order, or the first failure by place in the
    list is raised again."""
    out: list[Any] = [None] * len(items)
    failed: list[BaseException | None] = [None] * len(items)
    taken = itertools.count()
    lanes = min(k, len(items)) if k > 0 else len(items)

    async def lane() -> None:
        while True:
            i = next(taken)
            if i >= len(items):
                return
            try:
                out[i] = await round(items[i], i)
            except (TaskError, Failure) as e:
                failed[i] = e

    await asyncio.gather(*(lane() for _ in range(lanes)))
    for e in failed:
        if e is not None:
            raise e
    return out


def text(v: Any) -> str:
    """A value put into a string: text as it is, nothing for none, anything else as JSON."""
    if isinstance(v, str):
        return v
    if v is None:
        return ""
    return json.dumps(v, ensure_ascii=False, separators=(",", ":"))


async def wait_until(clock: Clock, at: str) -> None:
    """Wait until a moment given as an RFC 3339 string in UTC."""
    seconds = (datetime.fromisoformat(at.replace("Z", "+00:00")) - clock.now()).total_seconds()
    if seconds > 0:
        await clock.sleep(seconds)
"#;

impl<'a> Gen<'a> {
    fn var(&self, name: &str) -> String {
        format!("s.{}", py_name(name))
    }

    fn expr(&self, e: &TExpr) -> String {
        match e {
            TExpr::Str(s) => q(s),
            TExpr::Int(n) => n.to_string(),
            TExpr::Bool(b) => if *b { "True".into() } else { "False".into() },
            TExpr::Enum(v, _) => q(v),
            TExpr::None(_) => "None".into(),
            TExpr::Var { name, fields, ty } => {
                let mut s = self.var(name);
                for (i, f) in fields.iter().enumerate() {
                    // an absent field reads as None
                    if i + 1 == fields.len() && matches!(ty, Ty::Opt(_)) {
                        s = format!("{s}.get({})", q(f));
                    } else {
                        s = format!("{s}[{}]", q(f));
                    }
                }
                s
            }
            TExpr::Record { fields, .. } => format!("{{{}}}", fields.iter().map(|(f, x)| format!("{}: {}", q(f), self.expr(x))).collect::<Vec<_>>().join(", ")),
            TExpr::List { items, .. } => format!("[{}]", items.iter().map(|x| self.expr(x)).collect::<Vec<_>>().join(", ")),
            TExpr::Interp(parts) => {
                let out: Vec<String> = parts
                    .iter()
                    .map(|p| match p {
                        IPart::Lit(s) => q(s),
                        IPart::Hole(x) => format!("dd.text({})", self.expr(x)),
                    })
                    .collect();
                if out.is_empty() {
                    "\"\"".into()
                } else {
                    format!("({})", out.join(" + "))
                }
            }
        }
    }

    fn rounds_expr(&self) -> String {
        format!("[{}]", self.loops.iter().map(|l| format!("s.dd_loop_{l}")).collect::<Vec<_>>().join(", "))
    }

    fn node(&self, class: String, doc: String, order: (usize, usize), cx: &Ctx) -> Node {
        Node { class, doc, order, body: Vec::new(), targets: Vec::new(), end: cx.end }
    }

    fn field(&mut self, name: String, ty: &str, default: &str) {
        self.fields.insert(name, (ty.to_string(), default.to_string()));
    }

    /// The graph.py: the state, the dependencies, the nodes, the rounds' graphs, and `graph`.
    fn graph(&mut self, header: &str, rules: bool) -> String {
        let m = self.m;
        let flow_cx = |unhandled: Unhandled| Ctx { brk: None, unhandled, end: OUTPUT };
        let entry = match &m.on_failure {
            Some(block) => {
                // `on failure` runs for a task's error nothing took, then the run fails with it
                let mut refail = self.node("DD_refail".into(), "after `on failure`: the run fails with the task's error".into(), (usize::MAX, 0), &flow_cx(Unhandled::Fail));
                refail.line(0, "raise dd.Failure(s.dd_failed[\"kind\"], s.dd_failed[\"message\"])");
                self.nodes.push(refail);
                self.field("dd_failed".into(), "dict[str, Any] | None", "None");
                let on_failure = self.block(block, Jump::Node("DD_refail".into()), &flow_cx(Unhandled::Fail));
                self.block(&m.flow, Jump::End("None".into()), &flow_cx(Unhandled::OnFailure(on_failure)))
            }
            None => self.block(&m.flow, Jump::End("None".into()), &flow_cx(Unhandled::Fail)),
        };
        let first = match &entry {
            Jump::Node(n) => n.clone(),
            Jump::End(_) => {
                let mut done = self.node("DD_done".into(), "the flow does nothing".into(), (0, 0), &flow_cx(Unhandled::Fail));
                done.jump(0, &Jump::End("None".into()));
                self.nodes.push(done);
                "DD_done".into()
            }
        };

        let mut out = header.to_string();
        out.push_str(&format!("# {} v{}{}\n#\n", m.name, m.version, if m.description.is_empty() { String::new() } else { format!(": {}", m.description) }));
        out.push_str("# Run it with the input as a dict:\n#   await graph.run(inputs={…}, state=State(), deps=Deps(tasks=make_tasks(your_tasks), run_id=\"…\"))\n");
        out.push_str("# It returns the outputs (None when the flow ends without `succeed`), or raises runtime.Failure.\n");
        out.push_str("# The run lives in this process: a wait sleeps by Deps.clock, a callback's answer comes to\n# Deps.callbacks. graph.render() draws the flow.\n\n");
        out.push_str("from __future__ import annotations\n\nimport copy\nfrom dataclasses import dataclass, field\nfrom typing import Any\n\n");
        out.push_str("from pydantic_graph import BaseNode, End, GraphBuilder, GraphRunContext, StepContext\n\n");
        out.push_str("from . import runtime as dd\nfrom . import types as T\nfrom .tasks import Tasks\n\n\n");

        // the state: every variable, and where the loops are
        out.push_str("@dataclass\nclass State:\n    \"\"\"The flow's variables, and where its loops are.\"\"\"\n\n");
        for (v, ty) in &m.vars {
            let t = if matches!(ty, Ty::Opt(_)) { py_type(m, ty) } else { format!("{} | None", py_type(m, ty)) };
            out.push_str(&format!("    {}: {t} = None\n", py_name(v)));
        }
        for (n, (t, d)) in &self.fields {
            out.push_str(&format!("    {n}: {t} = {d}\n"));
        }
        if m.vars.is_empty() && self.fields.is_empty() {
            out.push_str("    pass\n");
        }

        out.push_str("\n\n");
        if rules {
            out.push_str("def dd_rules() -> Any:\n    from . import rules\n\n    return rules\n\n\n");
        }
        out.push_str("@dataclass\nclass Deps:\n    \"\"\"What the graph calls and waits by.\"\"\"\n\n");
        out.push_str("    tasks: Tasks\n    \"\"\"make_tasks(your_tasks, transport) of tasks.py\"\"\"\n");
        if rules {
            out.push_str("    rules: Any = field(default_factory=dd_rules)\n    \"\"\"the rules: rules.py, around the Python rulec generates\"\"\"\n");
        }
        out.push_str("    clock: dd.Clock = field(default_factory=dd.Clock)\n");
        out.push_str("    callbacks: dd.Callbacks = field(default_factory=dd.Callbacks)\n");
        out.push_str("    run_id: str = \"run\"\n    \"\"\"names the run in the idempotency keys and the callbacks' ids\"\"\"\n");

        let reach = |nodes: &[Node], from: &str| -> BTreeSet<String> {
            let by: BTreeMap<&str, &Node> = nodes.iter().map(|n| (n.class.as_str(), n)).collect();
            let mut seen = BTreeSet::new();
            let mut stack = vec![from.to_string()];
            while let Some(c) = stack.pop() {
                if !seen.insert(c.clone()) {
                    continue;
                }
                if let Some(n) = by.get(c.as_str()) {
                    for t in &n.targets {
                        if let Jump::Node(x) = t {
                            stack.push(x.clone());
                        }
                    }
                }
            }
            seen
        };
        let emit = |out: &mut String, nodes: &mut Vec<Node>, keep: &BTreeSet<String>| {
            nodes.sort_by_key(|n| n.order);
            for n in nodes.iter().filter(|n| keep.contains(&n.class)) {
                let mut ret: Vec<String> = n
                    .targets
                    .iter()
                    .map(|t| match t {
                        Jump::Node(c) => c.clone(),
                        Jump::End(_) => format!("End[{}]", n.end),
                    })
                    .collect();
                ret.dedup();
                if ret.is_empty() {
                    // a node that only fails: the run ends there
                    ret.push(format!("End[{}]", n.end));
                }
                out.push_str(&format!("\n\n@dataclass\nclass {}(BaseNode[State, Deps, \"{}\"]):\n    \"\"\"{}\"\"\"\n\n", n.class, n.end, n.doc));
                out.push_str(&format!("    async def run(self, ctx: GraphRunContext[State, Deps]) -> {}:\n", ret.join(" | ")));
                out.push_str("        s, deps = ctx.state, ctx.deps\n");
                for l in &n.body {
                    if l.is_empty() {
                        out.push('\n');
                    } else {
                        out.push_str(&format!("        {l}\n"));
                    }
                }
            }
        };

        let mut rounds = std::mem::take(&mut self.rounds);
        for r in &mut rounds {
            let keep = reach(&r.nodes, &r.entry);
            emit(&mut out, &mut r.nodes, &keep);
            let adds: Vec<String> = r.nodes.iter().filter(|n| keep.contains(&n.class)).map(|n| format!("{b}.node({})", n.class, b = format!("dd_{}", r.name))).collect();
            out.push_str(&format!(
                "\n\ndd_{name} = GraphBuilder(name={}, state_type=State, deps_type=Deps, input_type=Any, output_type=Any)\n\n\n@dd_{name}.step\nasync def {name}_begin(ctx: StepContext[State, Deps, Any]) -> {entry}:\n    return {entry}()\n\n\ndd_{name}.add(dd_{name}.edge_from(dd_{name}.start_node).to({name}_begin), {})\n{name} = dd_{name}.build()\n",
                q(&r.name),
                adds.join(", "),
                name = r.name,
                entry = r.entry
            ));
        }
        let mut nodes = std::mem::take(&mut self.nodes);
        let keep = reach(&nodes, &first);
        emit(&mut out, &mut nodes, &keep);

        // the start: the input, checked, into the state
        out.push_str(&format!("\n\ndd_graph = GraphBuilder(name={}, state_type=State, deps_type=Deps, input_type=dict[str, Any], output_type={OUTPUT})\n\n\n", q(&ident(&m.name))));
        out.push_str(&format!("@dd_graph.step\nasync def begin(ctx: StepContext[State, Deps, dict[str, Any]]) -> {first}:\n"));
        out.push_str("    if not T.is_WorkflowInput(ctx.inputs):\n        raise dd.Failure(\"Dandori.BadInput\", \"the execution's input does not have the declared shape\")\n");
        for (i, _) in &m.inputs {
            out.push_str(&format!("    ctx.state.{} = ctx.inputs.get({})\n", py_name(i), q(i)));
        }
        out.push_str(&format!("    return {first}()\n\n\n"));
        let adds: Vec<String> = nodes.iter().filter(|n| keep.contains(&n.class)).map(|n| format!("dd_graph.node({})", n.class)).collect();
        out.push_str(&format!("dd_graph.add(dd_graph.edge_from(dd_graph.start_node).to(begin), {})\ngraph = dd_graph.build()\n", adds.join(", ")));
        out
    }

    /// A block's nodes; the jump to its first node (or `next`, when it has none).
    fn block(&mut self, ss: &[TStmt], next: Jump, cx: &Ctx) -> Jump {
        let mut stmts = Vec::new();
        for s in ss {
            stmts.push(s);
            if matches!(s.kind, TK::Succeed { .. } | TK::Fail { .. } | TK::Break) {
                break;
            }
        }
        let mut j = next;
        for s in stmts.into_iter().rev() {
            j = self.stmt(s, j, cx);
        }
        j
    }

    /// What a task's error that no `on` takes does, in a node, for the error `e`.
    fn unhandled(n: &mut Node, depth: usize, cx: &Ctx) {
        match &cx.unhandled {
            Unhandled::OnFailure(j) => {
                n.line(depth, "s.dd_failed = {\"kind\": e.kind, \"message\": e.message}");
                n.jump(depth, j);
            }
            Unhandled::Fail => n.line(depth, "raise dd.Failure(e.kind, e.message) from None"),
            Unhandled::Raise => n.line(depth, "raise"),
        }
    }

    fn stmt(&mut self, s: &TStmt, next: Jump, cx: &Ctx) -> Jump {
        let m = self.m;
        let site = s.site;
        let line = s.line;
        match &s.kind {
            TK::Pass => next,
            TK::Break => cx.brk.clone().expect("lowering keeps break inside a loop"),
            TK::Assign { name, expr } => {
                let mut n = self.node(format!("S{site}_let"), format!("line {line}: let {name}"), (site, 0), cx);
                let x = self.expr(expr);
                n.line(0, &format!("{} = {x}", self.var(name)));
                n.jump(0, &next);
                self.push(n)
            }
            TK::Wait { seconds } => {
                let mut n = self.node(format!("S{site}_wait"), format!("line {line}: wait {seconds} seconds"), (site, 0), cx);
                n.line(0, &format!("await deps.clock.sleep({seconds})"));
                n.jump(0, &next);
                self.push(n)
            }
            TK::WaitUntil { at } => {
                let mut n = self.node(format!("S{site}_wait_until"), format!("line {line}: wait until {}", at.show()), (site, 0), cx);
                let x = self.expr(at);
                n.line(0, &format!("await dd.wait_until(deps.clock, {x})"));
                n.jump(0, &next);
                self.push(n)
            }
            TK::Succeed { fields } => {
                let mut n = self.node(format!("S{site}_succeed"), format!("line {line}: succeed"), (site, 0), cx);
                let out = if fields.is_empty() { "None".to_string() } else { format!("{{{}}}", fields.iter().map(|(f, e)| format!("{}: {}", q(f), self.expr(e))).collect::<Vec<_>>().join(", ")) };
                n.jump(0, &Jump::End(out));
                self.push(n)
            }
            TK::Fail { error, cause, .. } => {
                let mut n = self.node(format!("S{site}_fail"), format!("line {line}: fail {error}"), (site, 0), cx);
                let c = cause.as_ref().map(|c| self.expr(c)).unwrap_or_else(|| "None".into());
                n.line(0, &format!("raise dd.Failure({}, {c})", q(error)));
                self.push(n)
            }
            TK::Repeat { times, body } => {
                let again = Jump::Node(format!("S{site}_again"));
                self.field(format!("dd_loop_{site}"), "int", "0");
                self.loops.push(site);
                let inner = Ctx { brk: Some(next.clone()), ..cx.clone() };
                let first = self.block(body, again.clone(), &inner);
                self.loops.pop();
                let mut start = self.node(format!("S{site}_repeat"), format!("line {line}: repeat at most {times} times"), (site, 0), cx);
                start.line(0, &format!("s.dd_loop_{site} = 0"));
                start.jump(0, if *times > 0 { &first } else { &next });
                let mut round = self.node(format!("S{site}_again"), format!("line {line}: the next round"), (site, 1), cx);
                round.line(0, &format!("s.dd_loop_{site} += 1"));
                round.line(0, &format!("if s.dd_loop_{site} < {times}:"));
                round.jump(1, &first);
                round.jump(0, &next);
                self.nodes.push(round);
                self.push(start)
            }
            TK::For { var, list, max, parallel: None, body, result, .. } => {
                let again = Jump::Node(format!("S{site}_again"));
                let done = if result.is_some() { Jump::Node(format!("S{site}_done")) } else { next.clone() };
                self.field(format!("dd_loop_{site}"), "int", "0");
                self.field(format!("dd_items_{site}"), "list[Any]", "field(default_factory=list)");
                if result.is_some() {
                    self.field(format!("dd_out_{site}"), "list[Any]", "field(default_factory=list)");
                }
                self.loops.push(site);
                let inner = Ctx { brk: Some(done.clone()), ..cx.clone() };
                let first = self.block(body, again.clone(), &inner);
                self.loops.pop();
                let v = self.var(var);
                let mut start = self.node(format!("S{site}_for"), format!("line {line}: for {var} in {}", list.show()), (site, 0), cx);
                start.line(0, &format!("dd_items = {}", self.expr(list)));
                start.line(0, &format!("if len(dd_items) > {max}:"));
                start.line(1, &format!("raise dd.Failure(\"Dandori.TooManyItems\", {})", q(&format!("line {line}: the list has more than {max} items"))));
                start.line(0, &format!("s.dd_items_{site} = dd_items"));
                if result.is_some() {
                    start.line(0, &format!("s.dd_out_{site} = []"));
                }
                start.line(0, &format!("s.dd_loop_{site} = 0"));
                start.line(0, "if dd_items:");
                start.line(1, &format!("{v} = dd_items[0]"));
                start.jump(1, &first);
                start.jump(0, &done);
                let mut round = self.node(format!("S{site}_again"), format!("line {line}: the next round"), (site, 1), cx);
                if let Some((_, y)) = result {
                    round.line(0, &format!("s.dd_out_{site}.append({})", self.expr(y)));
                }
                round.line(0, &format!("s.dd_loop_{site} += 1"));
                round.line(0, &format!("if s.dd_loop_{site} < len(s.dd_items_{site}):"));
                round.line(1, &format!("{v} = s.dd_items_{site}[s.dd_loop_{site}]"));
                round.jump(1, &first);
                round.jump(0, &done);
                self.nodes.push(round);
                if let Some((r, _)) = result {
                    let mut end = self.node(format!("S{site}_done"), format!("line {line}: what the rounds yielded"), (site, 2), cx);
                    end.line(0, &format!("{} = s.dd_out_{site}", self.var(r)));
                    end.jump(0, &next);
                    self.nodes.push(end);
                }
                self.push(start)
            }
            TK::For { var, list, max, parallel: Some(k), body, result, locals } => {
                // a round is a graph of its own, which runs on a copy of the state
                self.field(format!("dd_loop_{site}"), "int", "0");
                let round_cx = Ctx { brk: None, unhandled: Unhandled::Raise, end: "Any" };
                let outer = std::mem::take(&mut self.nodes);
                let mut yielded = self.node(format!("S{site}_yield"), format!("line {line}: the round's end"), (site, usize::MAX), &round_cx);
                let y = result.as_ref().map(|(_, y)| self.expr(y)).unwrap_or_else(|| "None".into());
                yielded.jump(0, &Jump::End(y));
                self.nodes.push(yielded);
                self.loops.push(site);
                let first = self.block(body, Jump::Node(format!("S{site}_yield")), &round_cx);
                self.loops.pop();
                let round_nodes = std::mem::replace(&mut self.nodes, outer);
                let entry = match first {
                    Jump::Node(n) => n,
                    Jump::End(_) => format!("S{site}_yield"),
                };
                let name = format!("round_{site}");
                self.rounds.push(Round { name: name.clone(), entry, nodes: round_nodes });
                let mut n = self.node(format!("S{site}_for"), format!("line {line}: for {var} in {} in parallel", list.show()), (site, 0), cx);
                n.line(0, &format!("dd_items = {}", self.expr(list)));
                n.line(0, &format!("if len(dd_items) > {max}:"));
                n.line(1, &format!("raise dd.Failure(\"Dandori.TooManyItems\", {})", q(&format!("line {line}: the list has more than {max} items"))));
                n.line(0, "");
                n.line(0, "async def dd_round(dd_item: Any, dd_i: int) -> Any:");
                n.line(1, "r = copy.copy(s)");
                n.line(1, &format!("r.{} = dd_item", py_name(var)));
                for l in locals {
                    if l != var {
                        n.line(1, &format!("r.{} = None", py_name(l)));
                    }
                }
                n.line(1, &format!("r.dd_loop_{site} = dd_i"));
                n.line(1, &format!("return await {name}.run(state=r, deps=deps)"));
                n.line(0, "");
                n.line(0, "try:");
                n.line(1, &format!("dd_res = await dd.rounds(dd_items, dd.at_a_time({k}), dd_round)"));
                n.line(0, "except dd.TaskError as e:");
                Gen::unhandled(&mut n, 1, cx);
                if let Some((r, _)) = result {
                    n.line(0, &format!("{} = dd_res", self.var(r)));
                }
                n.jump(0, &next);
                self.push(n)
            }
            TK::Match { expr, arms } => {
                let x = match expr {
                    TExpr::Var { name, fields, .. } if m.case_index(name).is_some() => {
                        // a case that has not started reads as none
                        let v = self.var(name);
                        let mut s = v.clone();
                        for f in fields {
                            s.push_str(&format!("[{}]", q(f)));
                        }
                        format!("None if {v} is None else {s}")
                    }
                    other => self.expr(other),
                };
                let firsts: Vec<Jump> = arms.iter().map(|a| self.block(&a.body, next.clone(), cx)).collect();
                let mut n = self.node(format!("S{site}_match"), format!("line {line}: match {}", expr.show()), (site, 0), cx);
                n.line(0, &format!("dd_v = {x}"));
                for (a, first) in arms.iter().zip(&firsts) {
                    let mut parts = Vec::new();
                    if a.none {
                        parts.push("dd_v is None".to_string());
                    }
                    if a.some.is_some() {
                        parts.push("dd_v is not None".to_string());
                    }
                    if !a.values.is_empty() {
                        if expr.ty().inner() == &Ty::Bool {
                            for v in &a.values {
                                parts.push(format!("dd_v is {}", if v == "true" { "True" } else { "False" }));
                            }
                        } else {
                            parts.push(format!("dd_v in ({}{})", a.values.iter().map(|v| q(v)).collect::<Vec<_>>().join(", "), if a.values.len() == 1 { "," } else { "" }));
                        }
                    }
                    n.line(0, &format!("if {}:", parts.join(" or ")));
                    if let Some(v) = &a.some {
                        n.line(1, &format!("{} = dd_v", self.var(v)));
                    }
                    n.jump(1, first);
                }
                n.line(0, &format!("raise dd.Failure(\"Dandori.UnexpectedValue\", {})", q(&format!("line {line}: {} took a value that no arm names", expr.show()))));
                self.push(n)
            }
            TK::Call { target, callee, args, handlers } => self.call(s, target.as_ref(), callee, args, handlers, next, cx),
        }
    }

    fn push(&mut self, n: Node) -> Jump {
        let j = Jump::Node(n.class.clone());
        self.nodes.push(n);
        j
    }

    #[allow(clippy::too_many_arguments)]
    fn call(&mut self, s: &TStmt, target: Option<&Target>, callee: &Callee, args: &[(String, TExpr)], handlers: &[THandler], next: Jump, cx: &Ctx) -> Jump {
        let m = self.m;
        let site = s.site;
        let (cname, declared, result_ty) = match callee {
            Callee::Task(t) => {
                let task = &m.tasks[*t];
                (task.name.clone(), task.errors.iter().map(|e| q(&e.name)).collect::<Vec<_>>(), task.result.clone())
            }
            Callee::Rule(r) => (m.rules[*r].name.clone(), vec![], Some(Ty::Record(m.rules[*r].outputs))),
        };
        let firsts: Vec<Jump> = handlers.iter().map(|h| self.block(&h.body, next.clone(), cx)).collect();
        let mut parts: Vec<String> = args.iter().map(|(a, e)| format!("{}: {}", q(a), self.expr(e))).collect();
        if let Callee::Task(t) = callee {
            if m.tasks[*t].key {
                parts.push(format!("\"idempotency_key\": dd.key(deps.run_id, {site}, {})", self.rounds_expr()));
            }
        }
        let rs = retriers(m, callee);
        let declared = format!("[{}]", declared.join(", "));
        let mut n = self.node(format!("S{site}_{}", ident(&cname)), format!("line {}: {cname}", s.line), (site, 0), cx);
        let call = match callee {
            Callee::Rule(r) => format!("lambda: deps.rules.{}({{{}}})", render::rule_activity(&m.rules[*r].name), parts.join(", ")),
            Callee::Task(t) => {
                let task = &m.tasks[*t];
                let f = format!("deps.tasks.{}", method(&task.name));
                if task.callback {
                    let timeout = task.timeout.unwrap_or(86_400);
                    let mut with_id = parts.clone();
                    with_id.push("\"callback_id\": dd_id".into());
                    n.line(0, "dd_n = dd.counter()");
                    n.line(0, "");
                    n.line(0, "async def dd_call() -> Any:");
                    n.line(1, &format!("dd_id = dd.callback_id(deps.run_id, {site}, {}, next(dd_n))", self.rounds_expr()));
                    n.line(1, &format!("await {f}({{{}}})", with_id.join(", ")));
                    n.line(1, &format!("return await dd.await_callback(deps.callbacks, deps.clock, dd_id, {timeout})"));
                    n.line(0, "");
                    "dd_call".to_string()
                } else {
                    let timeout = task.timeout.map(|t| t.to_string()).unwrap_or_else(|| "None".into());
                    format!("lambda: dd.within({f}({{{}}}), {timeout})", parts.join(", "))
                }
            }
        };
        let reads = target.is_some() && result_ty.is_some();
        let invocation = format!("{}await dd.attempt({call}, {rs}, {declared}, deps.clock)", if reads { "dd_r = " } else { "" });
        if handlers.is_empty() && matches!(cx.unhandled, Unhandled::Raise) {
            n.line(0, &invocation);
        } else {
            n.line(0, "try:");
            n.line(1, &invocation);
            n.line(0, "except dd.TaskError as e:");
            for (h, first) in handlers.iter().zip(&firsts) {
                let conds: Vec<String> = h
                    .errors
                    .iter()
                    .map(|x| match x {
                        HErr::Failure => "True".to_string(),
                        HErr::Timeout => "e.kind == \"timeout\"".to_string(),
                        HErr::Declared(d) => format!("e.kind == {}", q(d)),
                    })
                    .collect();
                if conds.iter().any(|c| c == "True") {
                    n.jump(1, first);
                    break;
                }
                n.line(1, &format!("if {}:", conds.join(" or ")));
                n.jump(2, first);
            }
            if !handlers.iter().any(|h| h.errors.contains(&HErr::Failure)) {
                Gen::unhandled(&mut n, 1, cx);
            }
        }
        // the answer: its declared type, and for a case the states it may carry
        let var = match target {
            Some(Target::Let(v)) => Some(self.var(v)),
            Some(Target::Case(c)) => Some(self.var(&m.cases[*c].name)),
            None => None,
        };
        if let (Some(v), Some(ty)) = (var, &result_ty) {
            n.line(0, &format!("if not {}:", py_check(m, "dd_r", ty, "T.", 0)));
            n.line(1, &format!("raise dd.Failure(\"Dandori.BadResponse\", {})", q(&format!("line {}: the answer from {} does not have the declared shape", s.line, cname))));
            if let (Some(Target::Case(c)), Some((_, allowed))) = (target, m.monitors.get(&site)) {
                let field = &m.cases[*c].state_field;
                n.line(0, &format!("if dd_r[{}] not in ({}{}):", q(field), allowed.iter().map(|v| q(v)).collect::<Vec<_>>().join(", "), if allowed.len() == 1 { "," } else { "" }));
                n.line(
                    1,
                    &format!(
                        "raise dd.Failure(\"Dandori.UnexpectedState\", {})",
                        q(&format!("line {}: {} answered with a state the machine does not lead to here (expected one of {})", s.line, cname, allowed.join(", ")))
                    ),
                );
            }
            n.line(0, &format!("{v} = dd_r"));
        }
        n.jump(0, &next);
        self.push(n)
    }
}
