//! The workflow as TypeScript, for two platforms that run code by checkpoint and replay:
//! Temporal (the TypeScript SDK) and AWS Lambda durable functions (the durable execution
//! SDK for JavaScript). The two share the types, the shape of the code, the retries and the
//! checks; they differ in how a task, a wait and a callback are called.
//!
//! Temporal:
//! - `types.ts`: the records and enums, and a check for each (`is_<Type>`)
//! - `activities.ts`: the interface of the tasks, which you implement
//! - `rules.ts`: the rules as activities, around the TypeScript rulec generates
//! - `runtime.ts`: what the workflow code shares — retries, error kinds, keys
//! - `workflow.ts`: the workflow
//!
//! It means what the state machine means: a task is tried once by Temporal and retried by
//! the workflow's own code with the same retriers the ASL has, so that the two platforms
//! retry the same errors the same number of times; an answer is checked against its type
//! and, for a case, against the states the checker said it can be in; `on failure` runs for
//! the errors of tasks that nothing handled, and not for `fail` or a failed check.

use crate::diag::Diag;
use crate::model::*;
use crate::render::{self, ident};
use serde_json::Value;
use std::collections::BTreeSet;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Flavor {
    Temporal,
    Durable,
}

const TS_GLOBALS: &[&str] = &[
    "Array", "Boolean", "Date", "Error", "Function", "JSON", "Map", "Math", "Number", "Object", "Promise", "RegExp", "Set", "String", "Symbol",
    "WorkflowInput", "WorkflowOutput",
];

fn type_name(name: &str) -> String {
    let n = ident(&name.replace('.', "_"));
    if TS_GLOBALS.contains(&n.as_str()) {
        format!("{n}_")
    } else {
        n
    }
}

fn q(s: &str) -> String {
    serde_json::to_string(s).unwrap()
}

fn ts_type(m: &Model, t: &Ty) -> String {
    match t {
        Ty::Int | Ty::Num(_) => "number".into(),
        Ty::Str | Ty::Timestamp => "string".into(),
        Ty::Bool => "boolean".into(),
        Ty::Enum(e) => format!("T.{}", type_name(&m.enums[*e].name)),
        Ty::Record(r) => format!("T.{}", type_name(&m.records[*r].name)),
    }
}

/// A check that `x` is a well-formed value of `t`, as TypeScript. `p` is how the code
/// reaches types.ts: "" inside it, "T." from the workflow.
fn ts_check(m: &Model, x: &str, t: &Ty, p: &str) -> String {
    match t {
        Ty::Int | Ty::Num(_) => format!("Number.isInteger({x})"),
        Ty::Str => format!("typeof {x} === \"string\""),
        Ty::Timestamp => format!("(typeof {x} === \"string\" && {p}TIMESTAMP.test({x}))"),
        Ty::Bool => format!("typeof {x} === \"boolean\""),
        Ty::Enum(e) => format!("{p}{}_values.includes({x})", type_name(&m.enums[*e].name)),
        Ty::Record(r) => format!("{p}is_{}({x})", type_name(&m.records[*r].name)),
    }
}

fn used_types(m: &Model) -> (BTreeSet<usize>, BTreeSet<usize>) {
    let mut enums = BTreeSet::new();
    let mut recs = BTreeSet::new();
    fn visit(m: &Model, t: &Ty, enums: &mut BTreeSet<usize>, recs: &mut BTreeSet<usize>) {
        match t {
            Ty::Enum(e) => {
                enums.insert(*e);
            }
            Ty::Record(r) => {
                if recs.insert(*r) {
                    for (_, ft) in &m.records[*r].fields {
                        visit(m, ft, enums, recs);
                    }
                }
            }
            _ => {}
        }
    }
    for (_, t) in m.inputs.iter().chain(&m.outputs).chain(&m.vars) {
        visit(m, t, &mut enums, &mut recs);
    }
    for t in &m.tasks {
        visit(m, &t.result, &mut enums, &mut recs);
        for (_, pt) in &t.params {
            visit(m, pt, &mut enums, &mut recs);
        }
    }
    for s in m.all_stmts() {
        if let TK::Call { callee: Callee::Rule(r), .. } = &s.kind {
            visit(m, &Ty::Record(m.rules[*r].outputs), &mut enums, &mut recs);
            let rn = &m.rules[*r].name;
            for c in &m.rules[*r].info.inputs {
                if let crate::rulec::RType::Enum(en) = &c.ty {
                    if let Some(i) = m.enums.iter().position(|x| x.name == format!("{rn}.{en}")) {
                        enums.insert(i);
                    }
                }
            }
        }
    }
    for s in m.all_stmts() {
        if let TK::Call { args, .. } = &s.kind {
            for (_, e) in args {
                visit(m, &e.ty(), &mut enums, &mut recs);
            }
        }
    }
    (enums, recs)
}

pub fn build(m: &Model) -> Result<Vec<(String, String)>, Vec<Diag>> {
    build_flavor(m, Flavor::Temporal)
}

pub fn build_flavor(m: &Model, flavor: Flavor) -> Result<Vec<(String, String)>, Vec<Diag>> {
    let dir = ident(&m.name);
    let header = format!("// Code generated by dandori from {}. DO NOT EDIT.\n", m.source_file);
    let (enums, recs) = used_types(m);

    // types.ts
    let mut t = header.clone();
    t.push_str(&format!("// The records and enums of {} v{}, and a check for each.\n\n", m.name, m.version));
    t.push_str(&format!("export const TIMESTAMP = /{}/;\n\n", render::TIMESTAMP_RE.replace("\\\\", "\\")));
    for e in &enums {
        let en = &m.enums[*e];
        let n = type_name(&en.name);
        let vals: Vec<String> = en.values.iter().map(|v| q(v)).collect();
        t.push_str(&format!("export const {n}_values: readonly unknown[] = [{}];\n", vals.join(", ")));
        t.push_str(&format!("export type {n} = {};\n\n", vals.join(" | ")));
    }
    for r in &recs {
        let rd = &m.records[*r];
        let n = type_name(&rd.name);
        t.push_str(&format!("export interface {n} {{\n"));
        for (f, ft) in &rd.fields {
            t.push_str(&format!("  {}: {};\n", q(f), ts_type(m, ft).replace("T.", "")));
        }
        t.push_str("}\n\n");
        let mut conds = vec!["typeof v === \"object\"".to_string(), "v !== null".to_string()];
        for (f, ft) in &rd.fields {
            conds.push(ts_check(m, &format!("v[{}]", q(f)), ft, ""));
        }
        t.push_str(&format!("export function is_{n}(v: any): v is {n} {{\n  return {};\n}}\n\n", conds.join(" &&\n    ")));
    }
    t.push_str("export interface WorkflowInput {\n");
    for (n, ty) in &m.inputs {
        t.push_str(&format!("  {}: {};\n", q(n), ts_type(m, ty).replace("T.", "")));
    }
    t.push_str("}\n\n");
    let mut conds = vec!["typeof v === \"object\"".to_string(), "v !== null".to_string()];
    for (n, ty) in &m.inputs {
        conds.push(ts_check(m, &format!("v[{}]", q(n)), ty, ""));
    }
    t.push_str(&format!("export function is_WorkflowInput(v: any): v is WorkflowInput {{\n  return {};\n}}\n\n", conds.join(" &&\n    ")));
    t.push_str("export interface WorkflowOutput {\n");
    for (n, ty) in &m.outputs {
        t.push_str(&format!("  {}: {};\n", q(n), ts_type(m, ty).replace("T.", "")));
    }
    t.push_str("}\n");

    let called: BTreeSet<usize> = m.all_stmts().iter().filter_map(|s| match &s.kind { TK::Call { callee: Callee::Rule(r), .. } => Some(*r), _ => None }).collect();
    if flavor == Flavor::Durable {
        return durable_files(m, &dir, &header, t, &called);
    }

    // activities.ts
    let mut a = header.clone();
    a.push_str("// The tasks the workflow calls. Implement this interface and register it with the worker.\n");
    a.push_str("//\n");
    a.push_str("// - A declared error is thrown as ApplicationFailure.create({ type: \"<error>\", nonRetryable: true });\n");
    a.push_str("//   the workflow retries by itself, as its `retry` says, so Temporal's own retries are off.\n");
    a.push_str("// - A task with `key` gets `idempotency_key`: pass it on to the other side as it is.\n");
    a.push_str("// - A `callback` task hands Context.current().info.taskToken to whoever answers later and\n");
    a.push_str("//   throws CompleteAsyncError; the answer comes with client.activity.complete(taskToken, value).\n\n");
    a.push_str("import type * as T from \"./types\";\n\n");
    a.push_str("export interface Tasks {\n");
    for task in &m.tasks {
        let mut params: Vec<String> = task.params.iter().map(|(p, pt)| format!("{}: {}", q(p), ts_type(m, pt))).collect();
        if task.key {
            params.push("\"idempotency_key\": string".into());
        }
        a.push_str(&format!("  {}(args: {{ {} }}): Promise<{}>;\n", ident(&task.name), params.join("; "), ts_type(m, &task.result)));
    }
    a.push_str("}\n");

    // rules.ts
    let mut rules_ts = header.clone();
    rules_ts.push_str("// The rules the workflow calls, as activities around the TypeScript rulec generates.\n");
    rules_ts.push_str("// `rulec gen <rule> --out rulec` writes the modules these imports read.\n\n");
    for r in &called {
        let ts = &m.rules[*r].info.api["typescript"];
        let module = ts["module"].as_str().unwrap_or("rule").trim_end_matches(".ts").to_string();
        let mut names: BTreeSet<String> = BTreeSet::new();
        names.insert(ts["function"].as_str().unwrap_or("rule").to_string());
        for e in ts["enums"].as_array().unwrap_or(&vec![]) {
            let alias = e["alias"].as_str().unwrap_or("");
            if ts["params"].as_array().unwrap_or(&vec![]).iter().any(|p| p["type"].as_str() == Some(alias)) {
                names.insert(format!("parse{alias}"));
            }
        }
        rules_ts.push_str(&format!("import {{ {} }} from \"./rulec/typescript/{module}\";\n", names.into_iter().collect::<Vec<_>>().join(", ")));
    }
    rules_ts.push_str("\nexport const rules = {\n");
    for r in &called {
        let ru = &m.rules[*r];
        let ts = &ru.info.api["typescript"];
        let enum_aliases: Vec<String> = ts["enums"].as_array().unwrap_or(&vec![]).iter().map(|e| e["alias"].as_str().unwrap_or("").to_string()).collect();
        let mut args = Vec::new();
        let mut arg_types = Vec::new();
        for p in ts["params"].as_array().unwrap_or(&vec![]) {
            let name = p["name"].as_str().unwrap_or("");
            let ty = p["type"].as_str().unwrap_or("");
            let get = format!("args[{}]", q(name));
            if enum_aliases.iter().any(|x| x == ty) {
                args.push(format!("parse{ty}(String({get}))"));
                arg_types.push(format!("{}: string", q(name)));
            } else if ty == "boolean" {
                args.push(format!("Boolean({get})"));
                arg_types.push(format!("{}: boolean", q(name)));
            } else if ty == "string" {
                args.push(format!("String({get})"));
                arg_types.push(format!("{}: string", q(name)));
            } else {
                args.push(format!("BigInt({get})"));
                arg_types.push(format!("{}: number", q(name)));
            }
        }
        let mut outs = Vec::new();
        for o in ts["outputs"].as_array().unwrap_or(&vec![]) {
            let name = o["name"].as_str().unwrap_or("");
            let alias = o["alias"].as_str().unwrap_or("");
            let ty = o["type"].as_str().unwrap_or("");
            let v = if enum_aliases.iter().any(|x| x == ty) || ty == "boolean" || ty == "string" { format!("out.{alias}") } else { format!("Number(out.{alias})") };
            outs.push(format!("{}: {v}", q(name)));
        }
        rules_ts.push_str(&format!(
            "  async {}(args: {{ {} }}): Promise<Record<string, unknown>> {{\n    const out = {}({});\n    return {{ {} }};\n  }},\n",
            render::rule_activity(&ru.name),
            arg_types.join("; "),
            ts["function"].as_str().unwrap_or("rule"),
            args.join(", "),
            outs.join(", ")
        ));
    }
    rules_ts.push_str("};\n");

    // runtime.ts
    let runtime = format!("{header}{}", RUNTIME);

    // workflow.ts
    let mut g = Gen { m, out: String::new(), loops: vec![], flavor };
    let wf = g.workflow(&header, !called.is_empty());

    let mut files = vec![
        (format!("{dir}/types.ts"), t),
        (format!("{dir}/activities.ts"), a),
        (format!("{dir}/runtime.ts"), runtime),
        (format!("{dir}/workflow.ts"), wf),
    ];
    if !called.is_empty() {
        files.push((format!("{dir}/rules.ts"), rules_ts));
    }
    Ok(files)
}

/// The files for Lambda durable functions: the types, the tasks' interface, the shared
/// runtime, the handler, and for every rule it calls, the Lambda function it invokes (the
/// same handler the Step Functions target writes).
fn durable_files(m: &Model, dir: &str, header: &str, types_ts: String, called: &BTreeSet<usize>) -> Result<Vec<(String, String)>, Vec<Diag>> {
    let mut errs = Vec::new();
    for r in called {
        if m.rules[*r].lambda.is_none() {
            let ru = &m.rules[*r];
            errs.push(Diag::error(
                "E050",
                ru.line,
                1,
                format!("the rule `{}` is called, so it needs `lambda \"<function>\"` under `use rule` to be invoked", ru.name),
                format!("規則 `{}` は呼ばれているので、呼び出す先の `lambda \"<関数>\"` を `use rule` の下に書いてください", ru.name),
            ));
        }
    }
    if !errs.is_empty() {
        return Err(errs);
    }
    let mut t = header.to_string();
    t.push_str("// The tasks the workflow calls. Implement this interface and pass it to makeHandler.\n");
    t.push_str("//\n");
    t.push_str("// - A declared error is thrown as an Error whose name is the error's name:\n");
    t.push_str("//   const e = new Error(\"...\"); e.name = \"card_declined\"; throw e;\n");
    t.push_str("//   Each call runs in a step of its own, and the workflow retries by itself, as its `retry` says.\n");
    t.push_str("// - A task with `key` gets `idempotency_key`: pass it on to the other side as it is.\n");
    t.push_str("// - A `callback` task gets `callback_id` and returns once it has handed the id on. The answer\n");
    t.push_str("//   comes when the other side calls SendDurableExecutionCallbackSuccess with the id and the\n");
    t.push_str("//   answer as JSON, or SendDurableExecutionCallbackFailure with the error's name as ErrorType.\n\n");
    t.push_str("import type * as T from \"./types\";\n\n");
    t.push_str("export interface Tasks {\n");
    for task in &m.tasks {
        let mut params: Vec<String> = task.params.iter().map(|(p, pt)| format!("{}: {}", q(p), ts_type(m, pt))).collect();
        if task.key {
            params.push("\"idempotency_key\": string".into());
        }
        let result = if task.callback {
            params.push("\"callback_id\": string".into());
            "void".to_string()
        } else {
            ts_type(m, &task.result)
        };
        t.push_str(&format!("  {}(args: {{ {} }}): Promise<{}>;\n", ident(&task.name), params.join("; "), result));
    }
    t.push_str("}\n");
    let mut g = Gen { m, out: String::new(), loops: vec![], flavor: Flavor::Durable };
    let wf = g.workflow(header, !called.is_empty());
    let mut files = vec![
        (format!("{dir}/types.ts"), types_ts),
        (format!("{dir}/tasks.ts"), t),
        (format!("{dir}/runtime.ts"), format!("{header}{RUNTIME_DURABLE}")),
        (format!("{dir}/workflow.ts"), wf),
    ];
    for r in called {
        let (name, text) = crate::asl::lambda_handler(m, *r);
        files.push((format!("{dir}/{name}"), text));
    }
    Ok(files)
}

const RUNTIME_DURABLE: &str = r#"// What the generated handler shares. The code outside the steps runs again on every replay,
// so it reads nothing that can change between runs: the clock is read in a step.

import { CallbackTimeoutError, type DurableContext } from "@aws/durable-execution-sdk-js";

/** A task that failed after its retries, with the kind of error the `.flow` names it by. */
export class TaskError extends Error {
  readonly kind: string;
  constructor(kind: string, message: string) {
    super(message);
    this.kind = kind;
    this.name = "TaskError";
  }
}

/** A retrier, as the state machine's Retry has it: the kinds it takes ("*" is every kind). */
export interface Retrier {
  on: readonly string[];
  max: number;
  every: number;
  backoff: number;
}

/** The steps do not retry by themselves; the workflow does, as its `retry` says. */
export const noRetry = () => ({ shouldRetry: false });

/** The kind of an error from a step, an invoke or a callback: a declared error, "timeout", or "failure". */
export function kindOf(e: unknown, declared: readonly string[]): string {
  if (e instanceof CallbackTimeoutError) return "timeout";
  const cause = (e as { cause?: { name?: unknown } } | null)?.cause;
  const name = cause && typeof cause.name === "string" ? cause.name : e instanceof Error ? e.name : "";
  if (name === "Dandori.Timeout") return "timeout";
  if (declared.includes(name)) return name;
  return "failure";
}

function messageOf(e: unknown): string {
  const cause = (e as { cause?: { message?: unknown } } | null)?.cause;
  if (cause && typeof cause.message === "string") return cause.message;
  return e instanceof Error ? e.message : String(e);
}

/** Call once, and again as the retriers say, waiting between as Step Functions would. */
export async function attempt<R>(context: DurableContext, name: string, call: () => Promise<R>, retriers: readonly Retrier[], declared: readonly string[]): Promise<R> {
  const counts = retriers.map(() => 0);
  for (;;) {
    try {
      return await call();
    } catch (e) {
      const kind = kindOf(e, declared);
      let again = false;
      for (let i = 0; i < retriers.length; i++) {
        const r = retriers[i];
        if (r.on.includes(kind) || r.on.includes("*")) {
          if (counts[i] < r.max) {
            await context.wait(`${name} retry`, { seconds: Math.max(1, Math.ceil(r.every * Math.pow(r.backoff, counts[i]))) });
            counts[i]++;
            again = true;
          }
          break;
        }
      }
      if (!again) throw new TaskError(kind, messageOf(e));
    }
  }
}

/** A task's `timeout`, inside its step. */
export async function within<R>(p: Promise<R>, seconds: number | null): Promise<R> {
  if (seconds === null) return p;
  let timer: ReturnType<typeof setTimeout> | undefined;
  const late = new Promise<never>((_, reject) => {
    timer = setTimeout(() => {
      const e = new Error(`no answer in ${seconds} seconds`);
      e.name = "Dandori.Timeout";
      reject(e);
    }, seconds * 1000);
  });
  try {
    return await Promise.race([p, late]);
  } finally {
    clearTimeout(timer);
  }
}

/** A callback's answer comes as JSON text. */
export function parse(raw: unknown): unknown {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

/** The idempotency key of a call: the execution, the call's place, and the round of each loop around it. */
export function key(context: DurableContext, site: number, rounds: readonly number[]): string {
  return [context.executionContext.durableExecutionArn, String(site), ...rounds.map(String)].join("/");
}

/** A deliberate end of the workflow as failed. */
export function fail(error: string, cause: string | null): Error {
  const e = new Error(cause ?? "");
  e.name = error;
  return e;
}

/** A task's error that nothing handled ends the workflow with the error's kind. */
export function asFailure(e: unknown): unknown {
  return e instanceof TaskError ? fail(e.kind, e.message) : e;
}
"#;

const RUNTIME: &str = r#"// What the generated workflow code shares. It runs inside the workflow, so it uses nothing
// but @temporalio/workflow.

import { ActivityFailure, ApplicationFailure, TimeoutFailure, sleep, workflowInfo } from "@temporalio/workflow";

/** A task that failed after its retries, with the kind of error the `.flow` names it by. */
export class TaskError extends Error {
  constructor(
    public readonly kind: string,
    message: string,
  ) {
    super(message);
    this.name = "TaskError";
  }
}

/** A retrier, as the state machine's Retry has it: the kinds it takes ("*" is every kind). */
export interface Retrier {
  on: readonly string[];
  max: number;
  every: number;
  backoff: number;
}

/** The kind of an error from an activity: a declared error, "timeout", or "failure". */
export function kindOf(e: unknown, declared: readonly string[]): string {
  if (e instanceof ActivityFailure) {
    const c = e.cause;
    if (c instanceof TimeoutFailure) return "timeout";
    if (c instanceof ApplicationFailure && c.type && declared.includes(c.type)) return c.type;
  }
  return "failure";
}

function messageOf(e: unknown): string {
  if (e instanceof ActivityFailure && e.cause) return e.cause.message;
  return e instanceof Error ? e.message : String(e);
}

/** Call once, and again as the retriers say, waiting between as Step Functions would. */
export async function attempt<R>(call: () => Promise<R>, retriers: readonly Retrier[], declared: readonly string[]): Promise<R> {
  const counts = retriers.map(() => 0);
  for (;;) {
    try {
      return await call();
    } catch (e) {
      const kind = kindOf(e, declared);
      let again = false;
      for (let i = 0; i < retriers.length; i++) {
        const r = retriers[i];
        if (r.on.includes(kind) || r.on.includes("*")) {
          if (counts[i] < r.max) {
            await sleep(r.every * Math.pow(r.backoff, counts[i]) * 1000);
            counts[i]++;
            again = true;
          }
          break;
        }
      }
      if (!again) throw new TaskError(kind, messageOf(e));
    }
  }
}

/** The idempotency key of a call: the workflow, the call's place, and the round of each loop around it. */
export function key(site: number, rounds: readonly number[]): string {
  return [workflowInfo().workflowId, String(site), ...rounds.map(String)].join("/");
}

/** A deliberate end of the workflow as failed. */
export function fail(error: string, cause: string | null): ApplicationFailure {
  return ApplicationFailure.create({ type: error, message: cause ?? "", nonRetryable: true });
}

/** A task's error that nothing handled ends the workflow with the error's kind. */
export function asFailure(e: unknown): unknown {
  return e instanceof TaskError ? fail(e.kind, e.message) : e;
}
"#;

struct Gen<'a> {
    m: &'a Model,
    out: String,
    /// the counters of the loops around the current statement
    loops: Vec<usize>,
    flavor: Flavor,
}

impl<'a> Gen<'a> {
    fn line(&mut self, depth: usize, s: &str) {
        for _ in 0..depth {
            self.out.push_str("  ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn var(&self, name: &str) -> String {
        ident(name)
    }

    fn expr(&self, e: &TExpr) -> String {
        match e {
            TExpr::Str(s) => q(s),
            TExpr::Int(n) => n.to_string(),
            TExpr::Bool(b) => b.to_string(),
            TExpr::Enum(v, _) => q(v),
            TExpr::Var { name, fields, .. } => {
                let mut s = self.var(name);
                let is_input = self.m.inputs.iter().any(|(i, _)| i == name);
                for (i, f) in fields.iter().enumerate() {
                    if i == 0 && !is_input {
                        s.push('!');
                    }
                    s.push_str(&format!("[{}]", q(f)));
                }
                s
            }
        }
    }

    fn workflow(&mut self, header: &str, rules: bool) -> String {
        let m = self.m;
        self.out.push_str(header);
        self.out.push_str(&format!("// {} v{}{}\n\n", m.name, m.version, if m.description.is_empty() { String::new() } else { format!(": {}", m.description) }));
        let ret = if m.outputs.is_empty() { "null".to_string() } else { "T.WorkflowOutput".to_string() };
        if self.flavor == Flavor::Durable {
            self.out.push_str("import { StepSemantics, withDurableExecution, type DurableContext } from \"@aws/durable-execution-sdk-js\";\n");
            self.out.push_str("import type { Tasks } from \"./tasks\";\n");
            self.out.push_str("import * as T from \"./types\";\n");
            self.out.push_str("import * as dd from \"./runtime\";\n\n");
            self.out.push_str("/** The Lambda handler: `export const handler = makeHandler(yourTasks);` */\n");
            self.out.push_str("export function makeHandler(tasks: Tasks) {\n");
            self.out.push_str(&format!("  return withDurableExecution(async (input: T.WorkflowInput, context: DurableContext): Promise<{ret}> => {{\n"));
            self.out.push_str("    try {\n      return await run(input, context, tasks);\n    } catch (e) {\n      throw dd.asFailure(e);\n    }\n  });\n}\n\n");
            self.out.push_str(&format!("async function run(input: T.WorkflowInput, context: DurableContext, tasks: Tasks): Promise<{ret}> {{\n"));
            self.body();
            return std::mem::take(&mut self.out);
        }
        self.out.push_str("import { proxyActivities, sleep } from \"@temporalio/workflow\";\n");
        self.out.push_str("import type { Tasks } from \"./activities\";\n");
        if rules {
            self.out.push_str("import type { rules } from \"./rules\";\n");
        }
        self.out.push_str("import * as T from \"./types\";\n");
        self.out.push_str("import * as dd from \"./runtime\";\n\n");
        // one proxy per task, so each has its own timeout; Temporal does not retry, the workflow does
        for t in &m.tasks {
            let timeout = t.timeout.unwrap_or(if t.callback { 86_400 } else { 60 });
            self.out.push_str(&format!(
                "const {} = proxyActivities<Tasks>({{ startToCloseTimeout: \"{timeout} seconds\", retry: {{ maximumAttempts: 1 }} }}).{};\n",
                ident(&format!("task_{}", t.name)),
                ident(&t.name)
            ));
        }
        if rules {
            self.out.push_str("const rule_calls = proxyActivities<typeof rules>({ startToCloseTimeout: \"60 seconds\", retry: { maximumAttempts: 1 } });\n");
        }
        self.out.push('\n');
        let fname = ident(&m.name);
        self.out.push_str(&format!("export async function {fname}(input: T.WorkflowInput): Promise<{ret}> {{\n"));
        self.out.push_str("  try {\n    return await run(input);\n  } catch (e) {\n    throw dd.asFailure(e);\n  }\n}\n\n");
        self.out.push_str(&format!("async function run(input: T.WorkflowInput): Promise<{ret}> {{\n"));
        self.body();
        std::mem::take(&mut self.out)
    }

    /// The body of `run`: the input's check, the variables, the flow and `on failure`.
    fn body(&mut self) {
        let m = self.m;
        self.line(1, "if (!T.is_WorkflowInput(input)) throw dd.fail(\"Dandori.BadInput\", \"the execution's input does not have the declared shape\");");
        for (v, ty) in &m.vars {
            if m.inputs.iter().any(|(i, _)| i == v) {
                self.line(1, &format!("const {}: {} = input[{}];", self.var(v), ts_type(m, ty), q(v)));
            } else {
                self.line(1, &format!("let {}: {} | null = null;", self.var(v), ts_type(m, ty)));
            }
        }
        match &m.on_failure {
            Some(block) => {
                self.line(1, "try {");
                self.block(&m.flow, 2);
                self.line(2, "return null;");
                self.line(1, "} catch (dd_e) {");
                self.line(2, "if (!(dd_e instanceof dd.TaskError)) throw dd_e;");
                self.line(2, "// on failure");
                self.block(block, 2);
                self.line(2, "throw dd_e;");
                self.line(1, "}");
            }
            None => {
                self.block(&m.flow, 1);
                self.line(1, "return null;");
            }
        }
        self.out.push_str("}\n");
    }

    fn block(&mut self, ss: &[TStmt], d: usize) {
        for s in ss {
            self.stmt(s, d);
            if matches!(s.kind, TK::Succeed { .. } | TK::Fail { .. } | TK::Break) {
                break;
            }
        }
    }

    fn stmt(&mut self, s: &TStmt, d: usize) {
        let m = self.m;
        match &s.kind {
            TK::Pass => {}
            TK::Break => {
                let site = *self.loops.last().expect("lowering keeps break inside repeat");
                self.line(d, &format!("break loop_{site};"));
            }
            TK::Wait { seconds } => match self.flavor {
                Flavor::Temporal => self.line(d, &format!("await sleep({});", seconds * 1000)),
                Flavor::Durable => self.line(d, &format!("await context.wait({}, {{ seconds: {seconds} }});", q(&format!("{} wait", s.line)))),
            },
            TK::WaitUntil { at } => {
                let x = self.expr(at);
                match self.flavor {
                    Flavor::Temporal => self.line(d, &format!("await sleep(Math.max(0, Date.parse({x}) - Date.now()));")),
                    Flavor::Durable => {
                        // the clock is read in a step, so that a replay reads the same moment
                        let site = s.site;
                        self.line(d, &format!("const dd_now_{site} = await context.step({}, async () => Date.now(), {{ retryStrategy: dd.noRetry }});", q(&format!("{} now", s.line))));
                        self.line(d, &format!("const dd_wait_{site} = Math.ceil((Date.parse({x}) - dd_now_{site}) / 1000);"));
                        self.line(d, &format!("if (dd_wait_{site} > 0) await context.wait({}, {{ seconds: dd_wait_{site} }});", q(&format!("{} wait until", s.line))));
                    }
                }
            }
            TK::Succeed { fields } => {
                if fields.is_empty() {
                    self.line(d, "return null;");
                } else {
                    let parts: Vec<String> = fields.iter().map(|(f, e)| format!("{}: {}", q(f), self.expr(e))).collect();
                    self.line(d, &format!("return {{ {} }};", parts.join(", ")));
                }
            }
            TK::Fail { error, cause, .. } => {
                let c = cause.as_ref().map(|c| q(c)).unwrap_or_else(|| "null".into());
                self.line(d, &format!("throw dd.fail({}, {c});", q(error)));
            }
            TK::Repeat { times, body } => {
                let site = s.site;
                self.line(d, &format!("loop_{site}: for (let dd_loop_{site} = 0; dd_loop_{site} < {times}; dd_loop_{site}++) {{"));
                self.loops.push(site);
                self.block(body, d + 1);
                self.loops.pop();
                self.line(d, "}");
            }
            TK::Match { expr, arms } => {
                let x = match expr {
                    TExpr::Var { name, fields, .. } if m.case_index(name).is_some() => {
                        let v = self.var(name);
                        let mut s = v.clone();
                        for f in fields {
                            s.push_str(&format!("[{}]", q(f)));
                        }
                        format!("{v} === null ? null : {s}")
                    }
                    other => self.expr(other),
                };
                self.line(d, "{");
                self.line(d + 1, &format!("const dd_v: unknown = {x};"));
                for (i, a) in arms.iter().enumerate() {
                    let mut parts = Vec::new();
                    if a.none {
                        parts.push("dd_v === null".to_string());
                    }
                    if !a.values.is_empty() {
                        if expr.ty() == Ty::Bool {
                            for v in &a.values {
                                parts.push(format!("dd_v === {v}"));
                            }
                        } else {
                            parts.push(format!("[{}].includes(dd_v as string)", a.values.iter().map(|v| q(v)).collect::<Vec<_>>().join(", ")));
                        }
                    }
                    let kw = if i == 0 { "if" } else { "} else if" };
                    self.line(d + 1, &format!("{kw} ({}) {{", parts.join(" || ")));
                    self.block(&a.body, d + 2);
                }
                self.line(d + 1, "} else {");
                self.line(d + 2, &format!("throw dd.fail(\"Dandori.UnexpectedValue\", {});", q(&format!("line {}: {} took a value that no arm names", s.line, show(expr)))));
                self.line(d + 1, "}");
                self.line(d, "}");
            }
            TK::Call { target, callee, args, handlers } => self.call(s, target.as_ref(), callee, args, handlers, d),
        }
    }

    fn retriers(&self, callee: &Callee) -> String {
        let m = self.m;
        let v: Value = match callee {
            Callee::Rule(_) => serde_json::json!([
                { "ErrorEquals": ["States.Timeout"], "MaxAttempts": 0 },
                { "ErrorEquals": ["States.ALL"], "IntervalSeconds": crate::asl::RULE_RETRY_INTERVAL, "MaxAttempts": crate::check::RULE_RETRIES, "BackoffRate": crate::asl::RULE_RETRY_BACKOFF }
            ]),
            Callee::Task(t) => match &m.tasks[*t].retry {
                Some(r) => crate::asl::retriers(m, callee, &m.tasks[*t], r),
                None => serde_json::json!([]),
            },
        };
        let mut out = Vec::new();
        for r in v.as_array().unwrap() {
            let kinds: Vec<String> = r["ErrorEquals"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| {
                    let n = x.as_str().unwrap();
                    if n == "States.ALL" {
                        "*".to_string()
                    } else if n == "States.Timeout" {
                        "timeout".to_string()
                    } else {
                        match callee {
                            Callee::Task(t) => m.tasks[*t]
                                .errors
                                .iter()
                                .find(|(e, _)| render::asl_error(m, callee, &HErr::Declared(e.clone())).iter().any(|a| a == n))
                                .map(|(e, _)| e.clone())
                                .unwrap_or_else(|| n.to_string()),
                            Callee::Rule(_) => n.to_string(),
                        }
                    }
                })
                .collect();
            out.push(format!(
                "{{ on: [{}], max: {}, every: {}, backoff: {} }}",
                kinds.iter().map(|k| q(k)).collect::<Vec<_>>().join(", "),
                r["MaxAttempts"].as_u64().unwrap_or(3),
                r["IntervalSeconds"].as_u64().unwrap_or(1),
                r["BackoffRate"].as_f64().unwrap_or(2.0)
            ));
        }
        format!("[{}]", out.join(", "))
    }

    fn call(&mut self, s: &TStmt, target: Option<&Target>, callee: &Callee, args: &[(String, TExpr)], handlers: &[THandler], d: usize) {
        let m = self.m;
        let site = s.site;
        let (fn_expr, cname, declared, result_ty) = match callee {
            Callee::Task(t) => {
                let task = &m.tasks[*t];
                (ident(&format!("task_{}", task.name)), task.name.clone(), task.errors.iter().map(|(e, _)| q(e)).collect::<Vec<_>>(), task.result.clone())
            }
            Callee::Rule(r) => (format!("rule_calls.{}", render::rule_activity(&m.rules[*r].name)), m.rules[*r].name.clone(), vec![], Ty::Record(m.rules[*r].outputs)),
        };
        let mut parts: Vec<String> = args.iter().map(|(a, e)| format!("{}: {}", q(a), self.expr(e))).collect();
        if let Callee::Task(t) = callee {
            if m.tasks[*t].key {
                let rounds: Vec<String> = self.loops.iter().map(|l| format!("dd_loop_{l}")).collect();
                let ctx = if self.flavor == Flavor::Durable { "context, " } else { "" };
                parts.push(format!("\"idempotency_key\": dd.key({ctx}{site}, [{}])", rounds.join(", ")));
            }
        }
        let retriers = self.retriers(callee);
        let op = q(&format!("{} {}", s.line, cname));
        let invocation = match (self.flavor, callee) {
            (Flavor::Temporal, _) => format!("dd.attempt(() => {fn_expr}({{ {} }}), {retriers}, [{}])", parts.join(", "), declared.join(", ")),
            (Flavor::Durable, Callee::Rule(r)) => {
                let arn = q(m.rules[*r].lambda.as_deref().unwrap_or(""));
                format!("dd.attempt(context, {op}, () => context.invoke({op}, {arn}, {{ {} }}), {retriers}, [])", parts.join(", "))
            }
            (Flavor::Durable, Callee::Task(t)) => {
                let task = &m.tasks[*t];
                let method = ident(&task.name);
                if task.callback {
                    let timeout = task.timeout.unwrap_or(86_400);
                    let submit = q(&format!("{} {} submit", s.line, cname));
                    let mut with_id = parts.clone();
                    with_id.push("\"callback_id\": dd_id".into());
                    format!(
                        "dd.attempt(context, {op}, async () => {{\n{i}  const [dd_p, dd_id] = await context.createCallback({op}, {{ timeout: {{ seconds: {timeout} }} }});\n{i}  await context.step({submit}, async () => {{\n{i}    await tasks.{method}({{ {} }});\n{i}    return null;\n{i}  }}, {{ retryStrategy: dd.noRetry }});\n{i}  return dd.parse(await dd_p);\n{i}}}, {retriers}, [{}])",
                        with_id.join(", "),
                        declared.join(", "),
                        i = "  ".repeat(d + 2)
                    )
                } else {
                    // a call that changes things and carries no key must not run twice unseen
                    let semantics = if task.changes_things() && !task.key { "AtMostOncePerRetry" } else { "AtLeastOncePerRetry" };
                    let timeout = task.timeout.map(|t| t.to_string()).unwrap_or_else(|| "null".into());
                    format!(
                        "dd.attempt(context, {op}, () => context.step({op}, async () => dd.within(tasks.{method}({{ {} }}), {timeout}), {{ retryStrategy: dd.noRetry, semantics: StepSemantics.{semantics} }}), {retriers}, [{}])",
                        parts.join(", "),
                        declared.join(", ")
                    )
                }
            }
        };
        self.line(d, &format!("call_{site}: {{"));
        self.line(d + 1, &format!("// line {}: {cname}", s.line));
        self.line(d + 1, "let dd_r: unknown;");
        self.line(d + 1, "try {");
        self.line(d + 2, &format!("dd_r = await {invocation};"));
        self.line(d + 1, "} catch (dd_e) {");
        self.line(d + 2, "if (!(dd_e instanceof dd.TaskError)) throw dd_e;");
        for h in handlers {
            let conds: Vec<String> = h
                .errors
                .iter()
                .map(|e| match e {
                    HErr::Failure => "true".to_string(),
                    HErr::Timeout => "dd_e.kind === \"timeout\"".to_string(),
                    HErr::Declared(n) => format!("dd_e.kind === {}", q(n)),
                })
                .collect();
            self.line(d + 2, &format!("if ({}) {{", conds.join(" || ")));
            self.block(&h.body, d + 3);
            let ends = h.body.last().map(|x| matches!(x.kind, TK::Succeed { .. } | TK::Fail { .. } | TK::Break)).unwrap_or(false);
            if !ends {
                self.line(d + 3, &format!("break call_{site};"));
            }
            self.line(d + 2, "}");
        }
        self.line(d + 2, "throw dd_e;");
        self.line(d + 1, "}");
        // the answer: its declared type, and for a case the states it may carry
        let check = format!("({})", ts_check(m, "dd_r", &result_ty, "T."));
        self.line(d + 1, &format!("if (!{check}) throw dd.fail(\"Dandori.BadResponse\", {});", q(&format!("line {}: the answer from {} does not have the declared shape", s.line, cname))));
        let var = match target {
            Some(Target::Let(v)) => Some(self.var(v)),
            Some(Target::Case(c)) => Some(self.var(&m.cases[*c].name)),
            None => None,
        };
        if let (Some(Target::Case(c)), Some((_, allowed))) = (target, m.monitors.get(&site)) {
            let field = &m.cases[*c].state_field;
            self.line(
                d + 1,
                &format!(
                    "if (![{}].includes(dd_r[{}])) throw dd.fail(\"Dandori.UnexpectedState\", {});",
                    allowed.iter().map(|v| q(v)).collect::<Vec<_>>().join(", "),
                    q(field),
                    q(&format!("line {}: {} answered with a state the machine does not lead to here (expected one of {})", s.line, cname, allowed.join(", ")))
                ),
            );
        }
        if let Some(v) = var {
            self.line(d + 1, &format!("{v} = dd_r;"));
        }
        self.line(d, "}");
    }
}

fn show(e: &TExpr) -> String {
    match e {
        TExpr::Var { name, fields, .. } => std::iter::once(name.clone()).chain(fields.iter().cloned()).collect::<Vec<_>>().join("."),
        TExpr::Str(s) => s.clone(),
        TExpr::Int(n) => n.to_string(),
        TExpr::Bool(b) => b.to_string(),
        TExpr::Enum(v, _) => v.clone(),
    }
}
